### ISSUE TITLE
DataViewer 打开 Dialog 时闪退

### ISSUE THREAD

**Issue by sunfkny** [DGP-Studio/Snap.Genshin#10]
只有 Dialog 打开100%复现，打开其他项不会闪退
[snap_genshin_dataviewer_crash.log](https://github.com/DGP-Studio/Snap.Genshin/files/6291275/snap_genshin_dataviewer_crash.log)

**Comment by Lightczx** [comment]
fixed today！

**Comment by Lightczx** [comment]
fixed this release！
