### ISSUE TITLE
新桌面便签挺好的

### ISSUE THREAD

**Issue by nyano** [DGP-Studio/Snap.Genshin#100]
就是老问题
1.因为现在这种情况,我多账号,要一个一个开...每次都要开一下,每次开机都得手动点N下...更加的增加了步骤...
2.我是老版本升级过来的..直接跳错.12.30版本有cookie问题.必须删cookie解决.当然新版本不存在这问题了

3.主界面右上3个.既然我登录了多账号了.选择账号能不能直接选多账号角色?毕竟现在实际上并没有单一账号多ID...我得手动切一下.

4.便签在首次设定多账号cookie后,需要手动关闭后打开才能 显示其他账号.

**Comment by Lightczx** [comment]
1和3以后会看情况做，4还请详细描述一下

**Comment by nyano** [comment]
4主页面添加新账号cookie后,右下角 实时便签未能显示除了主账号外的其他账号信息.必须手动退出后打开才能显示.账号信息来点桌面便签.

**Comment by Lightczx** [comment]
这个是已知bug，下版本会修复

**Comment by Lightczx** [comment]
3这个功能研究了一下我觉得不可以实现
