### ISSUE TITLE
功能性建议

### ISSUE THREAD

**Issue by nyano** [DGP-Studio/Snap.Genshin#102]
1.由于mete的集成.开机启动总是自启主界面.但长远来讲 ,我只想看桌面便笺,而桌面便笺得自己一个一个点.由于多账号分割.我得点多次.能不能设定开机启动主界面自动不显?
2.双击\单击右下角图标不显示主界面.仅能通过右键点击显示.
3.在alt+tab界面下.因为多账号分割,显示为多个UI.如果多账号过多...
4.桌面便笺不记录放置位置.每次都会回归原始地点,需要手动 拖动.
5.强烈希望桌面便笺能自启!
6.主界面右上角能显示多账号信息,而不是我要一个一个账号选择[签到\便笺等]
7.养成计算能否合并计算结果并导出excel或集中显示?这是非常棒的功能!
8.插件得从哪里获取?
9.右上角启动器总是误点.能否 放在ID的左边?
10.桌面便笺取消了点击及时更新的优点.我只能等待设定的最低8分钟后的自动更新.希望能够还原手动更新的办法

**Comment by Lightczx** [comment]
主界面是必须显示的，已经写死了（任务栏的图标由主窗体负责首次创建），除非进行大量的底层改动否则不可能实现
桌面便笺的自动带出，便笺的位置 会在后续的版本添加
点击图标打开主界面的功能下版本会添加
在 alt tab 界面中显示 目前被定性为bug，后续的版本会移除显示
标题栏内的选择账号过于复杂，短期内不会考虑合并，同时标题栏的顺序目前也不考虑更改
如果是嫌签到繁琐可以在设置中打开每日首次启动签到
养成计算暂时还没有改动的打算，需要更多的使用体验反馈才会去考虑下一步功能
插件 目前反正我是没看见有人开发，等后面有人开发了sg会做进一步的更改
桌面便笺的即时更新还在考虑，因为理论上没必要实时，8分钟才回复1点

**Comment by nyano** [comment]
启动主界面问题.不需要直接隐藏,有很多软件就是显示一下,然后建立个事件.启动后再关闭窗口,主要还是自动化的问题.但这不是大问题
关于及时更新,是因为我把几个账号都刷了,但是是在8分钟内就完成了,而便笺还没更新=>主要是为了看全部恢复时间.但也不是什么必要需求
非常感谢

**Comment by Lightczx** [comment]
1，4，5 已经实装

**Comment by ss22219** [comment]
玩家信息查询或许可以调用getUserGameRolesByCookie API获取自身uid，方便查询自己的信息

**Comment by Lightczx** [comment]
会考虑的

**Comment by denghahaxixi** [comment]
现在有个解锁帧率功能需要管理员，但是似乎没有开机以管理员身份启动，可以自己电脑上手动添加或者加一个以管理员方式启动？谢谢

**Comment by Lightczx** [comment]
> 现在有个解锁帧率功能需要管理员，但是似乎没有开机以管理员身份启动，可以自己电脑上手动添加或者加一个以管理员方式启动？谢谢

可以属性里自己改管理员权限

**Comment by denghahaxixi** [comment]
> > 现在有个解锁帧率功能需要管理员，但是似乎没有开机以管理员身份启动，可以自己电脑上手动添加或者加一个以管理员方式启动？谢谢
> 
> 可以属性里自己改管理员权限

谢谢
