### ISSUE TITLE
延续性cookie bug

### ISSUE THREAD

**Issue by nyano** [DGP-Studio/Snap.Genshin#103]
此bug在老版本中也存在:
cookie失效后,无法重新添加,确认新cookie有效的情况下,可以输入进[添加新账号]中,但不显示.
手动解决办法:删除cookielist.dat中对应的值.并重启后才能解决.
但是在桌面便笺中数据未同步.似乎cookie数据不是同一个.
即使手动删除了cookielist.dat中的数据,老数据仍然存在在便笺中,但是为空数据,不显示cookie失效.
更新了cookie数据后.主程序正常,重启后便笺中同时显示同个账号老数据(无数据)和新数据
电脑重启后,发现主程序中cookie正常,便笺中仍未老数据(无数据),新数据失踪.

注意:手动添加cookie,如果不手动删除cookielist.dat数据,并重启软件,新cookie无法添加到主程序中..(不跳错,有效,但不显示信息)

**Comment by Lightczx** [comment]
桌面便笺中的数据确实与cookie列表中的数据不完全同步
现有的版本并未考虑cookie失效的问题，该问题会在后续版本修复

**Comment by Lightczx** [comment]
fixed
