### ISSUE TITLE
【功能性建议】集成帧率解锁

### ISSUE THREAD

**Issue by ssXue** [DGP-Studio/Snap.Genshin#107]
https://gitee.com/Euphony_Facetious/genshin-fps-unlock 原神解锁FPS限制

**Comment by Lightczx** [comment]
https://github.com/DGP-Studio/DGP.Genshin.FPSUnlocking
前天刚完成的转 C# ，目前还在测试稳定性，我们的原意是让 @DawnFz 先测试发布新版本，
但是他也还在测试，可能我们会更先完成测试。

**Comment by Lightczx** [comment]
已经更新
