### ISSUE TITLE
系统托盘图标

### ISSUE THREAD

**Issue by icimence** [DGP-Studio/Snap.Genshin#108]
能否在设置项中添加一个关闭后是否在系统托盘驻留的选择，我不是很习惯系统托盘有应用驻留导致每次关闭后都需要到系统托盘再关闭一次，或者是在关闭时进行询问

**Comment by Lightczx** [comment]
系统托盘图标的开启关闭功能会在其他功能稳定后尝试添加
最近问题有点多，可能会延后几个版本

**Comment by Lightczx** [comment]
已经更新
