### ISSUE TITLE
目前我本人已经逐渐停止了此项目的开发，任何的Bug都不保证修复

### ISSUE THREAD

**Issue by Lightczx** [DGP-Studio/Snap.Genshin#11]
至于为什么：

可能是我已经逐渐失去了对原神的热情。
此项目永远不会Archive但我也不保证会主动去更新，如果想要修复bug，目前只能靠其他人的PR了

**Comment by Lightczx** [comment]
我回来了

**Comment by Warkeeper** [comment]
哈哈哈哈哈原神果然 yyds，是金苹果那个版本太香了吗？
