### ISSUE TITLE
检查更新没有用

### ISSUE THREAD

**Issue by Xx-wpc** [DGP-Studio/Snap.Genshin#110]
因为关掉了windows的提醒，之前每次更新的时候都是手动点了检查更新，最近几个版本都没有用，只能再去手动下载覆盖

**Comment by Lightczx** [comment]
？

**Comment by Xx-wpc** [comment]
这种情况是我的问题还是这个检查更新的问题呢？最近几个版本都是朋友告诉我有更新了，我都会尝试一下检查更新可以不可以用，发现没用后我再来下载最新的去覆盖进去的

**Comment by Lightczx** [comment]
检查更新按钮确实失去了作用，有检查更新的步骤，但是后续的判断被暂时断开了
目前只有启动时的检查能够正常的按预期工作
我们正在为设置页面计划一个新的检查更新模块，

**Comment by Lightczx** [comment]
新的更新模块不会依赖Windows通知

**Comment by Xx-wpc** [comment]
> 检查更新按钮的正确设置时，可以确认更新的设置，但 目前正在进行更新，目前 正在破坏正常正常的功能，有正常工作的检查功能。
好的，那我知道啦，辛苦你们了！
