### ISSUE TITLE
抽卡记录分析功能提议

### ISSUE THREAD

**Issue by emako** [DGP-Studio/Snap.Genshin#111]
首先一点是，开放的API只能得到近6个月抽卡记录，必然要自己本地存一份，像下面我用工具导出的excel格式就很完美，这个excel格式被另一个工具支持分析，这个分析做的挺不错，还带成就展示，自己试了一下可以编译成web静态版。

能否考虑加入导出excel功能和并入这个分析工具的功能？-->不太想自己fork一版本啊

Genshin Gacha Export | 原神抽卡记录导出
> https://github.com/sunfkny/genshin-gacha-export

Genshin Gacha Analyzer | 原神抽卡记录分析工具
> https://github.com/voderl/genshin-gacha-analyzer

**Comment by emako** [comment]
这个是自己合并的仓库：
> https://github.com/emako/genshin-gacha

**Comment by laincat** [comment]
https://github.com/DGP-Studio/Snap.Genshin/wiki/StandardFormat

**Comment by Lightczx** [comment]
我们有导出功能啊，祈愿界面右上角的三个点是没加载出来么

**Comment by Lightczx** [comment]
顺带一提，你发的两个工具目前都已经支持了uigf格式，是可以完美的进行数据交互的
