### ISSUE TITLE
使用体验相关建议

### ISSUE THREAD

**Issue by noeru-desu** [DGP-Studio/Snap.Genshin#112]
1. 顶部的`每日签到`工具栏不会在第二天刷新，导致第二天签到需要重新启动程序
2. 希望可以将`自动签到`改为每天签到时间刷新时自动进行签到，而不是在程序启动时进行
3. `旅行札记`工具栏希望添加手动刷新按钮
4. 启动器首页`公告`与`活动`希望添加浏览器跳转功能
5. 另外我的`实时便笺`工具栏是完全空白的，不知道这是不是我个人的问题

感谢项目维护者的付出

**Comment by Lightczx** [comment]
1. 签到栏没有考虑过跨日问题，这个确实是疏忽了
2. 会考虑的
3. 旅行札记每次打开时都会刷新，不需要添加刷新按钮（因为打开操作本身就是）
[详细代码](https://github.com/DGP-Studio/Snap.Genshin/blob/f164a094e12785e75463f7d5ac6446f9429226cc/DGP.Genshin/ViewModels/TitleBarButtons/JourneyViewModel.cs)
4. 这个以前做过，后面会按实际体验恢复
5. 米游社权限没开，可以去米游社里开一下，下版本会在设置里加入强制开启开关

**Comment by Lightczx** [comment]
新版已经有了相应的改动
