### ISSUE TITLE
[使用体验] win11会出现图片模糊的情况

### ISSUE THREAD

**Issue by lvmodan** [DGP-Studio/Snap.Genshin#115]
![Snipaste_2022-01-15_17-50-16](https://user-images.githubusercontent.com/18571337/149617560-fde49f9a-83fc-4b48-919c-465c370c2a6d.png)
![Snipaste_2022-01-15_17-55-44](https://user-images.githubusercontent.com/18571337/149617703-a59f6996-bd3a-451c-b41d-de3629dfbbd3.png)

windows11，ui显示经常会变模糊。 切换窗口大小，模糊图片变清晰
触发方法： 
1 点击设置，鼠标悬浮到任意选项即可。切换窗口无效。移开鼠标恢复。
2 历史祈愿，点击有祈愿记录的日期，第一次展示的获取物品是模糊的。 切换窗口大小，图片变清晰
感谢项目维护者的付出

**Comment by Lightczx** [comment]
dotnet/wpf#707
https://docs.microsoft.com/en-us/answers/questions/505672/weird-rendering-issues-in-wpf-apps.html
---
简言之：你的音频驱动将它自己通过DirectX注入到了 Snap Genshin 来优化Snap Genshin 的音频输出体验
要解决这个问题需要查询你的音频驱动（有时可能是其他笔记本控制中心类App）的注入黑名单，将Snap Genshin 添加到黑名单中
重启后就不会有渲染问题了
