### ISSUE TITLE
启动游戏按钮的问题

### ISSUE THREAD

**Issue by LucaLin233** [DGP-Studio/Snap.Genshin#117]
点击启动按钮后不管是选择游戏本体或者是官方启动器，打开的游戏都是窗口的，不是全屏的，需要进设置一下窗口再设置回全屏才行，请问有没有什么解决办法

**Comment by Lightczx** [comment]
保存账号的时候需要确保游戏处于全屏下
启动之前检查一下下方的设置内有没有开启全屏模式

**Comment by LucaLin233** [comment]
> 保存账号的时候需要确保游戏处于全屏下
> 启动之前检查一下下方的设置内有没有开启全屏模式

这个我好像保存的时候没有开游戏来着，全屏游戏的按钮我好像没有找到，我晚上再去检查检查，谢谢回复

**Comment by Lightczx** [comment]
启动游戏面板可以滚动的

**Comment by LucaLin233** [comment]
> 启动游戏面板可以滚动的

我也是刚发现。。我太蠢了佬
