### ISSUE TITLE
关于导入 UIGF Json 文件时抽卡记录异常重复的bug

### ISSUE THREAD

**Issue by CHxCOOH** [DGP-Studio/Snap.Genshin#121]
这个 bug 让我一度以为是 Genshin Wish Export 导出的 Json 格式有问题，直到我用本软件自己导出又导入，duang——

![原始数据](https://raw.githubusercontent.com/CHxCOOH/GitHubImages/main/ScreenShots/Snipaste_2022-01-27_02-20-22.png)

导入失败提示格式错误之后，抽卡记录变成了这样：

![导入第一次](https://raw.githubusercontent.com/CHxCOOH/GitHubImages/main/ScreenShots/Snipaste_2022-01-27_02-21-00.png)

重复导入……

注意，导入又导出的部分显然是把原始数据逆序后又拼到原始数据后面了，后续每导入一次就新增一份上去。不太熟悉这块，就不猜测原因了。

![导入第二次](https://raw.githubusercontent.com/CHxCOOH/GitHubImages/main/ScreenShots/Snipaste_2022-01-27_02-21-44.png)

![导入第三次](https://raw.githubusercontent.com/CHxCOOH/GitHubImages/main/ScreenShots/Snipaste_2022-01-27_02-22-56.png)

另外顺便测试了一下，导入导出 Excel 并没有这个问题。

**Comment by CHxCOOH** [comment]
再看了一下，或许一开始就没有打算考虑用户重复导入 Json 的情况？

不过导入 Genshin Wish Export 的时候还是会弹窗提示失败，但实际上是导入成功的。

**Comment by Lightczx** [comment]
已知的版本bug，下版本修复

**Comment by Lightczx** [comment]
至于数据重复的问题sg是不可能解决的，gwe导出的数据有id不正确的问题
