### ISSUE TITLE
抽卡统计界面欧非判定不合理，及代码拼写问题

### ISSUE THREAD

**Issue by PriceHu** [DGP-Studio/Snap.Genshin#125]
目前程序对用户抽卡的欧非判定依据是一下代码：
https://github.com/DGP-Studio/Snap.Genshin/blob/8bb57ff21d1111b14e3164a2e61909329f7d371c/DGP.Genshin/Service/GachaStatistic/StatisticBuilder.cs#L265-L283

其中，`predicatedCount`值来源于一下代码片段：
https://github.com/DGP-Studio/Snap.Genshin/blob/8bb57ff21d1111b14e3164a2e61909329f7d371c/DGP.Genshin/Service/GachaStatistic/StatisticBuilder.cs#L142

这里以角色池五星为例讨论。根据代码，判定一个用户是非洲人的**边界条件**可以描述为：对于一个用户的所有抽卡次数，该用户抽到五星的频率**等于**卡池的综合概率。也就是说，只要用户抽到五星的频率**低于综合概率**，就被判定为**非洲人**。这显然是不合理的。

一个显而易见的例子是：当前游戏角色池五星综合概率为1.6%，五星期望值约为62.5抽，一个玩家平均63抽一个五星应当是正常范畴，然而根据代码判定，若这名玩家当前一共抽取了630次，已有9个五星，平均63抽一个，则距离上一个五星已经63抽，代码返回的`predicatedCount5`值为`-5`，是非洲人。这与通常对抽卡运气差的定义显然是不符的。

同时，该段代码对下一五星的预测抽数建立在用户已抽取的所有记录之上。这是不合理的，因为游戏中每个五星的抽数是相互独立的。一个人前20个五星平均80抽一个并不意味着他下一个五星就可以一发入魂。概率论只告诉我们当他抽卡次数足够多的时候，一个五星花费的抽数会逐渐接近62.5。

**建议**：修改抽卡统计界面的欧非判定标准，以一个五星抽数的概率分布为参考，取50%或某一合理数值作为区间设为常态。

另：上述代码所在文件中，`predicted`一词疑似多处拼写有误，错写为`predicatedCount`。

Reference: [用一千万抽，揭示原神抽卡系统全部细节_哔哩哔哩BiliBili](https://www.bilibili.com/video/BV19Y411W7W5)

**Comment by Lightczx** [comment]
拼写问题已经纠正
但是关于欧菲与预计的问题没太看明白，还请详细讲讲
或者提交PR

**Comment by PriceHu** [comment]
_此处以角色池为例。_

### 卡池机制

原神卡池中五星角色的概率为1.6%实际上是一个综合概率，表示从零开始恰好抽到时，花费抽数期望的倒数。根据公告描述，角色池五星的基础概率实际为0.6%，若仅计算90保底，其综合概率约为1.43%。因此假设卡池机制为在**一定抽数都没有抽到五星后**，每抽抽到五星的概率**开始线性上升**，直到第九十抽达到100%，计算得到的结果为，从第74抽开始概率上升。最终模型可见参考链接。

### 目前欧非判定机制的问题

- 目前的机制会导致**大量玩家被判定为非洲人**。现有代码看起来在使用**综合概率**预测下一个五星何时抽到，并以此判断欧非（你就算这次保底，五星也很多了/你就算下次抽到了，你的五星也不多），但经过简单的换算，就可以获得，当前非洲人的判定界限为五星的**期望抽数**。平均获得五星花费的抽数大于期望值就被判为非。然而，期望是一个平均数，这个数并不代表大多数人的抽数都在平均数一下，就像对于`{1, 9, 9, 9, ... , 9}`这串数而言，平均值显然比9小，但小于9的只有一个1。如果获得五星的平均抽数**服从正态分布**，那么现有机制会**将50%的玩家判定为非洲人**。实际情况我会再算一下，晚些补充。而且根据计算和统计结果，每次出五星，抽数都集中在78抽附近，在五星数量较少的情况下（新人和白嫖），将标准线设为期望抽数的62.5，更容易与体感不符。
- 随着抽卡次数的增加，被判定为正常的范围将越来越狭窄。按上一点的说明，设一名玩家已经抽取了`n`次，获得`a`个五星，那么代码判断运气正常的范围是`a/(n+90) < 0.016 < a/n`，换算可得`0.016n < a < 0.016n + 1.44`。也就是说，随着抽卡次数不断增加，运气正常时可能拥有的五星数量的**取值范围宽度没有变化**，永远**只有1~2个可能取值**。而由于全部样本中`a`的可能取值越来越多，被判为正常的部分所占的**比例将会越来越小**。即，抽卡越多，越不容易是运气正常。这显然是不正确的。

### 下一个五星需要抽数预测的问题

这个预测没有太大意义。这个预测基于综合概率下五星的期望抽数，然而只有在样本趋近于无穷时，平均抽数才会趋近于期望值，普通玩家几千次的抽卡数样本太少。而且游戏中每一个五星都是相互独立的，就算真的前几十抽就抽出也不过是一个小概率事件。一个很简单的例子，一个玩家一共抽了两个五星，根据统计和模型计算他有很大概率平均一个花了70多抽，但这不意味着他下一个五星大概率只需要40抽。

很久没碰C#了，过段时间有空如果没修的话就尝试提个PR吧。
参考资料可以详细看看。

#### 参考: 
1. [用一千万抽，揭示原神抽卡系统全部细节_哔哩哔哩BiliBili](https://www.bilibili.com/video/BV19Y411W7W5)
2. [原神抽卡机制研究（一）——五星的保底机制](https://www.bilibili.com/read/cv8772558)
3. [基于千万级抽卡数据的补充统计](https://www.bilibili.com/read/cv14841352)

**Comment by Lightczx** [comment]
已经明白了意思，但是不太好修改，我选择摆烂

**Comment by PriceHu** [comment]
草

我想了想，决定写一个模拟器生成数据，直接用统计结果绘图，明天发上来，你可以根据模拟的结果选一个区间直接定死判断标准，直接改这个方法：
https://github.com/DGP-Studio/Snap.Genshin/blob/8bb57ff21d1111b14e3164a2e61909329f7d371c/DGP.Genshin/Service/GachaStatistic/StatisticBuilder.cs#L265-L283

要是你还摆，那我只好提PR了（

**Comment by Lightczx** [comment]
改这个连前置的除法也要一并修改的，但是在不知道明确的概率分布曲线的情况下我没什么办法

**Comment by PriceHu** [comment]
懒得算，直接做了几次100万数量级的模拟，仅供参考

结论是当抽数较少时，五星数量会偏少，数据偏极端。考虑到一个玩家一整年大小月卡买满才可获得约1000抽，萌新和老玩家体感上是有很大差距的。（我的数据落在了大概75%的位置，迫真非酋（；´д｀）ゞ）

**固定了抽到的五星数量去模拟一共抽了多少次：**
![image](https://user-images.githubusercontent.com/21653481/152095726-6b22d66b-7367-48b7-b002-9c23e36e706a.png)
![image](https://user-images.githubusercontent.com/21653481/152095760-78d33ec1-d32c-4484-9465-6544d2d8beab.png)
![image](https://user-images.githubusercontent.com/21653481/152095799-965ca77b-6c73-4a78-9017-a9dd711ea7bd.png)

**固定抽数模拟一共抽了多少五星：**
![image](https://user-images.githubusercontent.com/21653481/152100391-c6493a86-4182-41fc-9017-9eeb5dea658b.png)
![image](https://user-images.githubusercontent.com/21653481/152100667-c7d590e3-944c-4080-8d31-3f26f9708c17.png)
![image](https://user-images.githubusercontent.com/21653481/152100763-c7ca608c-1e7e-4340-b62a-0c24f78d726e.png)
