### ISSUE TITLE
实时便签显示不完整

### ISSUE THREAD

**Issue by forevemoe** [DGP-Studio/Snap.Genshin#127]
当账户绑定的用户为2人时，实时便签中第二个用户信息显示不完整。

拖动拉长应用无法改善。

![bug](https://user-images.githubusercontent.com/31949690/152099076-671abbb7-d88c-45e0-a1bd-0bd27c1ac584.png)

**Comment by Lightczx** [comment]
已经注意到了这个问题，下版本会进行调整

**Comment by Lightczx** [comment]
目前可以用底下的滚动条滚动查看

**Comment by Lightczx** [comment]
已经修改了
