### ISSUE TITLE
更新自动关闭后，没有进行安装操作

### ISSUE THREAD

**Issue by RiZhiZhaoYi** [DGP-Studio/Snap.Genshin#128]
sg打开后windows消息推送有更新，点击更新，等待下载完成，下载完成后sg应用卡顿几秒，然后被自动关闭，多次重复发现有几次自动关闭后还会自动打开，但并未安装更新。
之后尝试在设置里更新，仍然不行
重启电脑仍然不行
windows11

**Comment by LucaLin233** [comment]
> sg打开后windows消息推送有更新，点击更新，等待下载完成，下载完成后sg应用卡顿几秒，然后被自动关闭，多次重复发现有几次自动关闭后还会自动打开，但并未安装更新。 之后尝试在设置里更新，仍然不行 重启电脑仍然不行 windows11

我也是，试了好几次都没更新，也是win11

**Comment by TTTornado** [comment]
一样，看到软件目录里的DGP.Genshin.Updater.exe没了，多了个Package.zip，直接解压到当前目录之后更新成功
Windows11

**Comment by Lightczx** [comment]
2022.2.1版本的问题，该版本的更新包没有内置更新器，导致更新会失败，用updater文件夹里面的更新器更新一下就可以了
