### ISSUE TITLE
每次启动游戏后手柄键位设置都会恢复默认

### ISSUE THREAD

**Issue by TTTornado** [DGP-Studio/Snap.Genshin#129]
每次通过sg启动游戏后手柄键位设置都会被恢复默认，通过官方启动器启动游戏没有这个问题
似乎sg的账号配置中是包含键位设置的，感觉问题与此有关
Windows11

**Comment by noeru-desu** [comment]
我每天启动都得重新登录，调过的设置也会全部回溯，应该也是同样的问题吧

**Comment by TTTornado** [comment]
> 我每天启动都得重新登录，调过的设置也会全部回溯，应该也是同样的问题吧

似乎 这里 #118  也有人遇到了一样的问题
我改别的设置倒没有问题

**Comment by Lightczx** [comment]
改完设置后重新保存一下账号

**Comment by TTTornado** [comment]
> 改完设置后重新保存一下账号

有效，谢谢
