### ISSUE TITLE
建议在微软商店上发布

### ISSUE THREAD

**Issue by liangzhaoyuan12** [DGP-Studio/Snap.Genshin#130]
建议在微软商店上发布，可以减少使用者的安装步骤，在商店安装可以一键安装运行所需的环境

**Comment by Lightczx** [comment]
Microsoft Store 拒绝了我们的提交
理由是内容没有达到他们的要求

**Comment by liangzhaoyuan12** [comment]
我的天啊，这样的要求也也太高了吧，我看有一些人做了一个代码都不用几行的简易下载器都能上架。
不过，有一些地方确实也需要改进，比如说我每次电脑重启后再次打开那个软件时又要重新登录，对性能的优化也有待提升。
但是，这都过不了审核属实让我有点意外



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年02月15日 17:54 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [DGP-Studio/Snap.Genshin] 建议在微软商店上发布 (Issue #130) |

Microsoft Store 拒绝了我们的提交
理由是内容没有达到他们的要求

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
