### ISSUE TITLE
插件不知道怎么加载

### ISSUE THREAD

**Issue by Zichen3317** [DGP-Studio/Snap.Genshin#132]
如图，不知道怎么导入插件，重新开软件也不会加载，可能是我食用方法不对吧QAQ
![image](https://user-images.githubusercontent.com/76838041/152358362-63e3677f-fba9-47f6-accb-25270a72a23a.png)
![image](https://user-images.githubusercontent.com/76838041/152358401-57160497-23aa-4422-9284-9bf7b2084ed9.png)
![image](https://user-images.githubusercontent.com/76838041/152358432-c54fcab7-e4d9-43a3-bddf-378a53757184.png)

**Comment by Lightczx** [comment]
插件需要对应的版本才能正常使用

**Comment by Zichen3317** [comment]
很抱歉再打扰一下...我上面截图时的版本是最新的...但是还是不能用...不太明白您的意思...
![image](https://user-images.githubusercontent.com/76838041/152456671-3e123d5b-15d8-4330-830b-7766928ac0f9.png)

**Comment by candywzt** [comment]
插件是dll格式的，你把人家源码放进去了，去插件发布页面下载打包好的dll放进去就行
