### ISSUE TITLE
开机断网时自启无法识别cookie

### ISSUE THREAD

**Issue by nyano** [DGP-Studio/Snap.Genshin#145]
由于各种各样的原因，如管控软件、驱动等原因，开机前十几秒处于断网状态，而软件开启时大概需要对cookie进行验证，由于断网了，所以无法验证cookie，从而造成开机时直接跳提供cookie界面。
但是由于cookie本身并未失效，所以手动关闭窗口后重开，则可以直接进入。但仅保留主账号，小号等均失踪。
同时配置文件中发现，所有cookie均存在。
是否有办法加入断网验证机制（断网无法验证cookie，但是否可跟无效cookie进行区分处置） 
或降低开机自启顺序，等一会再打开？
亦或者其他办法

**Comment by Lightczx** [comment]
断网检测应该是正常工作的
至于为什么其他的Cookie无法请求到米游社的信息，还请提供一下用户设备ID

**Comment by nyano** [comment]
5FEF098101B37352DCCBC6E815242930
针对此问题的补充说明：
可能并非开机断网问题
1.复现：仅在一台设备上存在复现，另外电脑并未复现正常
2.情况仅发生在每日第一次开机，后续多次手动重启（maybe）或手动打开均未有错
3.移动网
复现情况如下：（显示的内容）
开机-》自动打开-》请输入cookie（首次打开状态）-》关闭
看根目录，【settings.json】和【cookielist.dat】存在多账号cookie，一切正常
再次打开-》更新-》丢失除第一个cookie外其他，文件更新
-》便签全失踪
-》手动重新添加相同cookie，正常添加

不知道哪个版本添加 自动保存设置 。。。

**Comment by Lightczx** [comment]
下版本修复

**Comment by Lightczx** [comment]
保存设置需要你手动退出SG，关机时SG无法保存设置
