### ISSUE TITLE
程序关闭后重新启动卡在校验Cookie有效性界面

### ISSUE THREAD

**Issue by ggfengxuan** [DGP-Studio/Snap.Genshin#150]
程序关闭后重新启动卡在校验Cookie有效性界面，再次关闭后可以重启，但是账号信息只会保留最后一个

**Comment by ggfengxuan** [comment]
设备ID:701460C700716EC3E5983B4B91EB89E7

**Comment by Lightczx** [comment]
1. 你的cookie可能已经失效了，在使用多cookie时请不要将老账号退出登录
2. 检查你的cookie是否包含中文标点

**Comment by ggfengxuan** [comment]
> 

好的，谢谢！确实是退出老账号登录的新账号，使用的自动获取cookie的功能，添加新账号的时候，页面显示的是老账号已登录状态，所以退出后登录新账号(我之前也是用的自动获取，不过不记得登录状态是什么样子的了)

**Comment by ggfengxuan** [comment]
> 1. 你的cookie可能已经失效了，在使用多cookie时请不要将老账号退出登录
> 2. 检查你的cookie是否包含中文标点

改为 无痕模式+手动获取后正常，再次感谢！
