### ISSUE TITLE
关于版本2022.2.8.26更新移除大地图的意见

### ISSUE THREAD

**Issue by SImaHongcai** [DGP-Studio/Snap.Genshin#151]
虽然「新增 自定义网页功能，可用在导航栏自行添加网页」，但是「移除了 大地图页面」令我不是很理解，而「新增 自定义网页功能」似乎是为了弥补「移除了 大地图页面」而加入进来的。
谢谢！

**Comment by Yuzi0201** [comment]
确实，为什么要移除大地图？求解释，难道是官方告上门来了？
