### ISSUE TITLE
一个在国外经常用的抽卡网站，或许可考虑联系？

### ISSUE THREAD

**Issue by LaoshuBaby** [DGP-Studio/Snap.Genshin#152]
https://paimon.moe/wish/

![图片](https://user-images.githubusercontent.com/42690037/153020565-16e7a153-3507-4817-a338-66c782254adf.png)

甚至有全球各国语言的i18n支持

它的仓库是这个

https://github.com/MadeBaruna/paimon-moe

<s>我们如何才能令这个网站支持[UIGF](https://github.com/DGP-Studio/Snap.Genshin/wiki/StandardFormat)呢？（issue肯定要提）</s>

----

update 1:

https://github.com/MadeBaruna/paimon-moe/issues/182 下有人给出了[sunfkny/genshin-gacha-export](https://github.com/sunfkny/genshin-gacha-export)版excel转换方案

**Comment by Masterain98** [comment]
写了一个专门针对Paimon.moe的祈愿记录导出工具，如有有人需要，可以尝试

[Masterain98/Paimon.moe-WishHistory-UIGF-Exporter](https://github.com/Masterain98/Paimon.moe-WishHistory-UIGF-Exporter)

Paimon.moe只接受英文数据Excel导入且格式很花... UIGF目前只有中文版，所以直接互相转换数据是不可行的
