### ISSUE TITLE
启动游戏就闪退

### ISSUE THREAD

**Issue by King-Nameless** [DGP-Studio/Snap.Genshin#155]
开了无边框和解锁帧率功能，启动游戏本体就自动闪退了，第一次用的是2022.2.6.6之前的一个版本，启动游戏没问题，看到更新提示，更新2022.2.6.6后就会闪退了，现在的2022.2.8.26也闪退
另外不添加一个启动游戏后自动最小化到托盘的功能吗

**Comment by Lightczx** [comment]
闪退是个例问题，我们无法解决，你可以试试删除settings,json 重新设置SG
最小化的功能会加的
