### ISSUE TITLE
设置经常无故被还原

### ISSUE THREAD

**Issue by Rorschachina** [DGP-Studio/Snap.Genshin#166]
如题，我做的设置，隔一两天就会被重置，变成初始的样子，是不是因为重新获取了cookie？

**Comment by Rorschachina** [comment]
另外，虽然现在可以记住调整的窗口大小了（手动拖动调整），但是最大化的状态并不会记住，能不能支持下记住最大化？

**Comment by Lightczx** [comment]
最大化状态逻辑上不应该记忆
设置应该是偶发现象，需要更准确的行为描述才能定性
你可以尝试更新到最新版本看看还会不会有此类问题
