### ISSUE TITLE
体验方面的几个问题

### ISSUE THREAD

**Issue by char-46** [DGP-Studio/Snap.Genshin#167]
1. 通过启动游戏按钮直接启动游戏本体并保存账号密码，重启电脑之后依然要求重新输入账号密码。
2. 签到工具跨日不更新，需要去设置内手动签到。
3. 希望角色 wiki 显示更多内容，如角色信息或不同天赋等级的属性。

**Comment by char-46** [comment]
在重启电脑之前，直接使用保存的信息可以登录，重启电脑之后，之前保存的信息失效。
似乎是原神客户端的问题，不使用 Snap.Genshin 的情况下重启电脑也需要重新登录。

**Comment by CHxCOOH** [comment]
似乎是最近（几天前）官方启动器更新之后才出现的问题，我印象里，更新之前是没有这个问题的

**Comment by char-46** [comment]
可能是我很长时间（一周以上）才重启一次电脑感觉不明显，但是这个问题更早之前也是存在的。

**Comment by Lightczx** [comment]
最新版已经修复了保存的问题

**Comment by svonx** [comment]
是否可以修改一下保存账号时备注的体验？比如备注为空的时候不给予保存，备注与已经存在的时候提醒是否替换之类的，蟹蟹。

**Comment by CHxCOOH** [comment]
同意楼上，现在的逻辑在退出账号也会保存，保存时也会顺带保存画质选项（不过这个比较难解决）

还有一点，启动器每次打开都是选择保存的第一个账号，可否增加一个记忆功能，自动选择上次打开的账号？

**Comment by TimeEndDoctor** [comment]
点击更新并安装只会下载但是不安装

**Comment by Lightczx** [comment]
> 点击更新并安装只会下载但是不安装

2.1 2.2版本的bug，手动下新版本覆盖一下

**Comment by sistinafibe** [comment]
签到工具跨日不更新确实很影响体验

**Comment by Lightczx** [comment]
最新版已经允许刷新签到
