### ISSUE TITLE
米游社添加账号问题

### ISSUE THREAD

**Issue by 1061875478** [DGP-Studio/Snap.Genshin#172]
添加新的米游社账号后客户端不会刷新账号信息，重启后只剩新加的账号

**Comment by Lightczx** [comment]
版本？

**Comment by 1061875478** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
