### ISSUE TITLE
为什么不能从genshin-wish-export导入记录？

### ISSUE THREAD

**Issue by hjsj121** [DGP-Studio/Snap.Genshin#180]
![屏幕截图 2022-02-20 213902](https://user-images.githubusercontent.com/99570060/154845396-5a82e6ef-5da1-453f-80ad-9f36c35e8ea2.png)
![屏幕截图 2022-02-20 214047](https://user-images.githubusercontent.com/99570060/154845417-e7dedec8-834a-4d7a-b8ee-6a365a764bac.png)

**Comment by Lightczx** [comment]
仅 0.8.2 版本以上的gge支持正确的uigf格式，较低的版本格式就是不正确的
