### ISSUE TITLE
DGP.Genshin.exe 占用了0.1M的内存就闪退了

### ISSUE THREAD

**Issue by erichuanp** [DGP-Studio/Snap.Genshin#182]
没找到log文件...不知道为何闪退...
尝试过手动下载新版本覆盖、删除unrelated files启动、和从旧版本升级，均闪退
|Windows版本|Runtime|SnapGenshin版本|
|:----:|:----:|:----:|
|Windows 11 21H2|.NET 6.0.2|[2022.2.19.20](https://github.com/DGP-Studio/Snap.Genshin/releases/tag/2022.2.19.20)|

经测试[2022.2.18.18](https://github.com/DGP-Studio/Snap.Genshin/releases/tag/2022.2.18.18)是可用的。

**Comment by erichuanp** [comment]
对比了一下[2022.2.19.20](https://github.com/DGP-Studio/Snap.Genshin/releases/tag/2022.2.19.20)和[2022.2.18.18](https://github.com/DGP-Studio/Snap.Genshin/releases/tag/2022.2.18.18)之间的commits，感觉没什么会引起闪退啊😢

**Comment by erichuanp** [comment]
草，[2022.2.18.18](https://github.com/DGP-Studio/Snap.Genshin/releases/tag/2022.2.18.18)也寄了

**Comment by Lightczx** [comment]
.NET **Desktop** Runtime 6.0.2

**Comment by Xrafece** [comment]
+1，我也寄了，win11

**Comment by LittleNightmare** [comment]
我傻了。。。为啥win10也。。好奇怎么锁这个版本

事件查看器日志
```
Application: DGP.Genshin.exe
CoreCLR Version: 6.0.21.52210
.NET Version: 6.0.0
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileLoadException: Could not load file or assembly 'PresentationFramework, Version=6.0.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'PresentationFramework, Version=6.0.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'

```

**Comment by Lightczx** [comment]
求求你们去更新一下 .NET Desktop Rumtime 6.0.2
