### ISSUE TITLE
自动更新后程序闪退

### ISSUE THREAD

**Issue by Jackxwb** [DGP-Studio/Snap.Genshin#189]
启动程序，提示自动更新，一会，弹出一个黑色的命令行，命令行关闭后就全退出了。
此时手动双击图标，没有界面出来，从任务管理器里面看，DGP.Genshin.exe在双击之后只运行了很短一下就自己退出了。
由于程序目录下面的log文件夹是空的，我只好放到火绒剑里面记录启动情况了
[log.txt](https://github.com/DGP-Studio/Snap.Genshin/files/8132276/log.txt)
上面这段记录里面程序启动了系统的 WerFault.exe 程序，并且写入了`C:\Windows\appcompat\Programs\Amcache.hve`这个文件里面，也一起附上了，不知有无帮助（手动改成txt后缀才能上传，用文本编辑器打开里面内容有乱码有明文）
[Amcache.hve.txt](https://github.com/DGP-Studio/Snap.Genshin/files/8132299/Amcache.hve.txt)

补充：
系统版本 Windows 10 1909 [版本 10.0.18363.1734]
更新前，正常使用

**Comment by Lightczx** [comment]
#182
