### ISSUE TITLE
DS失效了

### ISSUE THREAD

**Issue by hudawei** [DGP-Studio/Snap.Genshin#19]
大佬，听说米游社DS失效了，必须用米游社2.10以上版本才能查别人的角色和战绩，还有救吗？

**Comment by Lightczx** [comment]
DS失效和我们无关，我们使用的是2.10.1的DS
实测仍可以获取

**Comment by Lightczx** [comment]
DS确实有问题了，算法和以前不同了，我仍在尝试反向中
