### ISSUE TITLE
新建议

### ISSUE THREAD

**Issue by nyano** [DGP-Studio/Snap.Genshin#193]
1.桌面便签还能回来么-,-我发现以前一个alt+enter看到所有挺好的
2.使用的提醒功能能不能合并在一个提醒戳内,由于多个账号会导致不断的一个一个显示...按照设定的如8分钟更新机制显示,直接一个大框显示出来比较舒服点
3.提醒设置能否可设定按每个账号独立设置.毕竟可能存在主号和小号可能优先级不同.
4.[养成计算]中的账号选择,仅能提前在[账号管理]中选择后,才能选择
5.角色\武器列中的材料类别,能否显示名称(或鼠标选择展示).由于某些材料的图标看起来一样.如果详细看这些资料的话,仍然可能要访问某些网站.
6.有木有一种可能.胡桃数据库添加个筛选功能.比如四星和五星筛选等?

**Comment by Lightczx** [comment]
13456 不做
2 下版本实现
