### ISSUE TITLE
关于SG中启动【游戏本体】的问题

### ISSUE THREAD

**Issue by yourean** [DGP-Studio/Snap.Genshin#200]
在使用【SG→启动游戏→游戏本体】时，总是以1080p窗口化启动。

进入游戏更改其他分辨率后，退出游戏，重新以【SG→启动游戏→游戏本体】方式启动原神时，还是以1080p窗口化启动，无法以上次的分辨率启动游戏。

关于此问题，不知有无解决方案。

**Comment by Lightczx** [comment]
在修改过游戏内的设置后需要重新保存账号
