### ISSUE TITLE
每次点击侧边栏的开始游戏时都会提示新建账号

### ISSUE THREAD

**Issue by Keviince** [DGP-Studio/Snap.Genshin#202]
每次点击侧边栏的开始游戏时都会提示新建账号，点击确定或按ESC后会在账号列表内新增一个名为空的项

**Comment by Lightczx** [comment]
那你新建啊，把老的账号删了保留新的

**Comment by JoshYEn** [comment]
感谢您的回复。

我无法判断网络环境是否存在问题，因为米游社部分的功能一直是正常的。可否请您提供一个思路？

**Comment by Lightczx** [comment]
你的MAC地址IP地址等一切用于区分联网设备的特征中的任何一项发生了变化
原神就会重新生成注册表值，生成的值由于与SG保存的任何一项不匹配就会导致对话框出现

**Comment by JoshYEn** [comment]
了解了，再次感谢您的回复。

**Comment by Mo3et** [comment]
给个解决思路 根据楼上的回复和个人情况 可能是使用了Proxy导致的 某些Proxy路线的Auto Config会导致IP地址发生变更
同种情况我也在Steam遇到了 解决方法就是先关了然后打开完再开 或者线路稳定就用固定线路 不要用Auto

**Comment by JoshYEn** [comment]
> 给个解决思路 根据楼上的回复和个人情况 可能是使用了Proxy导致的 某些Proxy路线的Auto Config会导致IP地址发生变更 同种情况我也在Steam遇到了 解决方法就是先关了然后打开完再开 或者线路稳定就用固定线路 不要用Auto

感谢，我现在的网络环境是上级路由自动分配的公网IP，所以确实经常改动。。。没得办法了。
