### ISSUE TITLE
养成计算功能，在没有添加任何清单的情况下，添加清单后，默认UI的文字提示不隐藏

### ISSUE THREAD

**Issue by Pinkuburu** [DGP-Studio/Snap.Genshin#212]
重现步骤
1、保持养成计算的清单为空，例如删除已经添加的清单
2、点击“我的角色”，随便添加一个清单
3、点击材料清单，即可复现
![image](https://user-images.githubusercontent.com/4962790/158226641-99b00c06-0c3b-419f-ae03-5f65b39cb0ce.png)
版本信息
![image](https://user-images.githubusercontent.com/4962790/158226756-33f6a6b1-eeb7-4fb9-9119-a8667641964c.png)

**Comment by Lightczx** [comment]
fixed
