### ISSUE TITLE
关于网络问题...

### ISSUE THREAD

**Issue by CzHUV** [DGP-Studio/Snap.Genshin#215]
FastGit选项从设置中删除了，现在不挂梯子无法自动更新。

**Comment by Masterain98** [comment]
国内用户的话更新包链接会一直是 [https://resource.snapgenshin.com/Publish.zip](https://resource.snapgenshin.com/Publish.zip)

你看下访问是否有问题；如果有问题，打开CMD，使用nslookup命令查看`resource.snapgenshin.com`的解析是否在国内

**Comment by CzHUV** [comment]
> 国内用户的话更新包链接会一直是 https://resource.snapgenshin.com/Publish.zip，使用的服务器全部在国内，不需要代理服务
> 
> 你看下访问是否有问题；如果有问题，打开CMD，使用nslookup命令查看`resource.snapgenshin.com`的解析是否在国内

这边国内可以正常打开，但是在snap genshin中无法直接通过“检查更新并安装”按钮来安装更新，必须挂梯子
也有可能是上一个版本不行，我这边已经更新成 Version 3.18 Build 2了

**Comment by Masterain98** [comment]
> > 国内用户的话更新包链接会一直是 https://resource.snapgenshin.com/Publish.zip，使用的服务器全部在国内，不需要代理服务
> > 
> > 你看下访问是否有问题；如果有问题，打开CMD，使用nslookup命令查看`resource.snapgenshin.com`的解析是否在国内
> 
> 这边国内可以正常打开，但是在snap genshin中无法直接通过“检查更新并安装”按钮来安装更新，必须挂梯子
> 也有可能是上一个版本不行，我这边已经更新成 Version 3.18 Build 2了

可以访问一下[https://patch.snapgenshin.com/getPatch](https://patch.snapgenshin.com/getPatch) 看channel字段值是否为cn

**Comment by Lightczx** [comment]
正式通道理论上不存在无法访问导致更新异常的问题
正式通道的更新服务器在国内是有加速的
如果是预览通道那确实会出现更新的问题，因为是纯GitHub提供的更新服务

**Comment by CzHUV** [comment]
> > > 国内用户的话更新包链接会一直是 [https://resource.snapgenshin.com/Publish.zip，使用的服务器全部在国内，不需要代理服务](https://resource.snapgenshin.com/Publish.zip%EF%BC%8C%E4%BD%BF%E7%94%A8%E7%9A%84%E6%9C%8D%E5%8A%A1%E5%99%A8%E5%85%A8%E9%83%A8%E5%9C%A8%E5%9B%BD%E5%86%85%EF%BC%8C%E4%B8%8D%E9%9C%80%E8%A6%81%E4%BB%A3%E7%90%86%E6%9C%8D%E5%8A%A1)
> > > 你看下访问是否有问题；如果有问题，打开CMD，使用nslookup命令查看`resource.snapgenshin.com`的解析是否在国内
> > 
> > 
> > 这边国内可以正常打开，但是在snap genshin中无法直接通过“检查更新并安装”按钮来安装更新，必须挂梯子
> > 也有可能是上一个版本不行，我这边已经更新成 Version 3.18 Build 2了
> 
> 可以访问一下https://patch.snapgenshin.com/getPatch/ 看channel字段值是否为cn

是cn，问题下次更新看看是否解决，这里先将这个问题close了，感谢帮助！

**Comment by CzHUV** [comment]
您好！
在这次更新之后，我依然无法通过大陆网络直接更新，还是需要挂梯子。

**Comment by Masterain98** [comment]
可以先参考下面这份文档来排查问题
[https://www.snapgenshin.com/documents/FAQ/update-errors.html](https://www.snapgenshin.com/documents/FAQ/update-errors.html)

**Comment by CzHUV** [comment]
> https://resource.snapgenshin.com/Publish.zip https://patch.snapgenshin.com/getPatch/ 看下这俩的访问情况
第一个网址：
![image](https://user-images.githubusercontent.com/100004265/159677722-bfe7b5ec-7eec-422b-a1c4-17c080da3e81.png)
第二个网址：
![image](https://user-images.githubusercontent.com/100004265/159677904-46c9efb2-97c1-4d60-aa5c-bab33c86007b.png)

**Comment by CzHUV** [comment]
补充：
https://resource.snapgenshin.com （去掉Publish.zip）可以正常访问，但当用户需要直接下载时，则会拒绝访问。

**Comment by Masterain98** [comment]
> 补充： https://resource.snapgenshin.com （去掉Publish.zip）可以正常访问，但当用户需要直接下载时，则会拒绝访问。

资源站中所有文件的下载都会403还是仅有Publish.zip会出现这样的问题？

**Comment by CzHUV** [comment]
> https://resource.snapgenshin.com/Publish.zip


您好，这网络情况挺奇特的，我刚刚反馈的时候还拒绝访问，这会再访问就行了。
另外，其他的链接也可以正常下载。

**Comment by CzHUV** [comment]
> > 补充： https://resource.snapgenshin.com （去掉Publish.zip）可以正常访问，但当用户需要直接下载时，则会拒绝访问。
> 
> 资源站中所有文件的下载都会403还是仅有Publish.zip会出现这样的问题？

现在的问题就是，我可以直接通过https://resource.snapgenshin.com/ 点击下载资源，但是无法通过您给的链接下载。
虽然俩都是一样的链接，但是您在回复里给我的拒绝访问。

**Comment by CzHUV** [comment]
另外，其他链接也是相同情况。

**Comment by CzHUV** [comment]
额在这里我先给您两位道个歉
我发现可能是我DNS设置的问题，我将我的DNS设置为了DNSPod的DNS，然后就可以访问并下载了，，
之前挂完梯子以后都是用360的dns优选还原，可能这就是问题所在吧。
总之，这个问题告一段落，感谢您两位的帮助。

**Comment by CzHUV** [comment]
话说我刚刚查了一下，发现360给我设置的是114dns，这边看你们的手册里有推荐114DNS，可否考虑一下将此条删去？

**Comment by CzHUV** [comment]
旧话重提
不能从Snap Genshin本身的检查更新中更新，还是得挂梯子（虽然挂个梯子也不是多难），若是想要不挂梯子下载，就必须跳转到Snap Genshin的国内资源站内下载Publish.zip
现在的问题就是不能从那个按钮直接下载（懒人不想替换快捷方式+安装），请问是不是那个按钮的指向网址错了？
