### ISSUE TITLE
武器池大保底显示不正确

### ISSUE THREAD

**Issue by syb024** [DGP-Studio/Snap.Genshin#220]
![image](https://user-images.githubusercontent.com/16432395/159608481-9a7e50fb-2275-4320-90c2-e3ec16ddd051.png)
[152915107.xlsx](https://github.com/DGP-Studio/Snap.Genshin/files/8329057/152915107.xlsx)

**Comment by Lightczx** [comment]
请不要混淆定轨和保底，我们无法统计你的定轨情况
