### ISSUE TITLE
[Bug]: 旧话重提，还是关于网络...

### ISSUE THREAD

**Issue by CzHUV** [DGP-Studio/Snap.Genshin#222]
### Windows 版本

19042.1586

### Snap Genshin 版本

2022 Version 3.25 Build 21

### Snap Genshin 用户设备ID

EA4D2A18959A26C2504A17F061AB272F

### 发生了什么？

旧话重提
这一次的问题可大可小，就看开发者们对它的态度了
无法从大陆点击检查更新后直接更新，DNS使用的DNSPod，点击检查更新后会出现“检查更新失败”的提示（挂上梯子后则会显示当前为最新版本）
当然，这个问题可以轻松的通过几个点击解决（指跳转到大陆资源站下载Publish.zip然后覆盖安装），所以我才说可大可小

但我在这里小小的提个建议，一般这些好感都是在细小的细节中培养出来的，若是连最新发布版本都不能使使用者轻松点击一下就懒人完成（尤其是在当下越来越多人喜欢这种设计），那我想即使您程序中做的再细节，做产品再用心，没有人关注的话，您的努力不久都付诸东流了吗?

虽然我自己也知道我作为个局外人来从高处判决你们是令人不满的，但我希望这些小小的建议能被采取。
感谢！

### Snap Genshin 用户守则及相关的隐私条款

- [x] 我同意遵守 Snap Genshin 用户守则及相关的隐私条款

**Comment by Lightczx** [comment]
可以使用 nslookup 检查一下 
```
patch.snapgenshin.com
```

```
resource.snapgenshin.com
```

看一下结果么

**Comment by Masterain98** [comment]
更新服务器和资源分发站点都是我处理的，所以来回答你的问题

> 这一次的问题可大可小，就看开发者们对它的态度了

我不知道您说的态度问题从何而来。你也是用GitHub的，你应该在中国大陆地区知道访问它是有困难的。它对开源社区是友好的，包括SG在内的开源项目能够通过GitHub分发新版本并通过API在程序内判断版本更新。这一切都是顺滑的，但前提是用户可以访问到GitHub。SG曾经使用的FastGit是一种方案，它通过反代GitHub来避免国内网络对GitHub域名/IP的针对性干扰。但它也是另一个开源项目，服务稳定性远远达不到我们期望的效果，所以我们决定自己分发安装包。我们已经为用户提供了GitHub以外的另一种选择，我们还需要改成什么态度呢？？？


> 当然，这个问题可以轻松的通过几个点击解决（指跳转到大陆资源站下载Publish.zip然后覆盖安装），所以我才说可大可小

当前，SG程序内的稳定通道下载源就是资源站的`Publish.zip`，所以我也不知道能怎么修复。7小时前，有大量用户汇报了更新问题，但是没有一个用户上传了有用的信息来允许我们判断究竟是哪一个步骤出现了问题。这一解决步骤已经写在了[官方文档中的常见问题](https://www.snapgenshin.com/documents/FAQ/update-errors.html)中。我写这篇明显长于其它文档的问题指引是为了收集一般用户会出现问题，但似乎并没有人在意，这我也实在是没有办法了。


> 若是连最新发布版本都不能使使用者轻松点击一下就懒人完成（尤其是在当下越来越多人喜欢这种设计），那我想即使您程序中做的再细节，做产品再用心，没有人关注的话，您的努力不久都付诸东流了吗?

我们不是大公司，没有资源去提供大公司敢担保的用户体验，我们只是做了能做的事。如果你不是开源社区开发者，你可能不知道**版本分发**对于在中国的开发者而言是一个多么困难的事情，它远比写出程序本身要困难。
写出程序，需要的是一台电脑，一个灵感和动手实践。
版本分发，需要的是钱。
我们以[腾讯云COS](https://cloud.tencent.com/document/product/436/53863)为例，使用它，SG肯定能高度稳定地分发版本。SG现在一个版本的安装包平均大小为14MB，假设当前有3000用户，一次版本更新的流量为(14 * 3000 / 1024 = 41GB)。在2月份，SG更新了13次，也就是(41 * 13 = 533 GB)。按照腾讯云的价格为(533 * 0.5 = 266.5元) 。这个价格应该没有哪个原神相关的开源项目能付得起，更何况这仅仅是SG使用云端资源中的一部分。
一些Android端的开源程序尚且可以找酷安这样的相对条件宽松的应用市场分发版本，我们Windows程序又能找谁呢？

**Comment by CzHUV** [comment]
> 可以使用 nslookup 检查一下
> 
> ```
> patch.snapgenshin.com
> ```
> 
> ```
> resource.snapgenshin.com
> ```
> 
> 看一下结果么
![image](https://user-images.githubusercontent.com/100004265/160214592-1a7260cd-3a0f-4574-9e4e-ecaffdca5d5d.png)

![image](https://user-images.githubusercontent.com/100004265/160214601-edaa9014-3c35-4633-b90f-f12670421d32.png)

**Comment by CzHUV** [comment]
> 更新服务器和资源分发站点都是我处理的，所以来回答你的问题
> 
> > 这一次的问题可大可小，就看开发者们对它的态度了
> 
> 我不知道您说的态度问题从何而来。你也是用GitHub的，你应该在中国大陆地区知道访问它是有困难的。它对开源社区是友好的，包括SG在内的开源项目能够通过GitHub分发新版本并通过API在程序内判断版本更新。这一切都是顺滑的，但前提是用户可以访问到GitHub。SG曾经使用的FastGit是一种方案，它通过反代GitHub来避免国内网络对GitHub域名/IP的针对性干扰。但它也是另一个开源项目，服务稳定性远远达不到我们期望的效果，所以我们决定自己分发安装包。我们已经为用户提供了GitHub以外的另一种选择，我们还需要改成什么态度呢？？？
> 
> > 当然，这个问题可以轻松的通过几个点击解决（指跳转到大陆资源站下载Publish.zip然后覆盖安装），所以我才说可大可小
> 
> 当前，SG程序内的稳定通道下载源就是资源站的`Publish.zip`，所以我也不知道能怎么修复。 7小时前，有大量用户汇报了更新问题，但是没有一个用户上传了有用的信息来允许我们判断究竟是哪一个步骤出现了问题。这一解决步骤已经写在了[官方文档中的常见问题](https://www.snapgenshin.com/documents/FAQ/update-errors.html)中。我写这篇明显长于其它文档的问题指引是为了收集一般用户会出现问题，但似乎并没有人在意，这我也实在是没有办法了。
> 
> > 若是连最新发布版本都不能使使用者轻松点击一下就懒人完成（尤其是在当下越来越多人喜欢这种设计），那我想即使您程序中做的再细节，做产品再用心，没有人关注的话，您的努力不久都付诸东流了吗?
> 
> 我们不是大公司，没有资源去提供大公司敢担保的用户体验，我们只是做了能做的事。如果你不是开源社区开发者，你可能不知道**版本分发**对于在中国的开发者而言是一个多么困难的事情，它远比写出程序本身要困难。 写出程序，需要的是一台电脑，一个灵感和动手实践。 版本分发，需要的是钱。 我们以[腾讯云COS](https://cloud.tencent.com/document/product/436/53863)为例，使用它，SG肯定能高度稳定地分发版本。SG现在一个版本的安装包平均大小为14MB，假设当前有3000用户，一次版本更新的流量为(14 * 3000 / 1024 = 41GB)。在2月份，SG更新了13次，也就是(41 * 13 = 533 GB)。按照腾讯云的价格为(533 * 0.5 = 266.5元) 。这个价格应该没有哪个原神相关的开源项目能付得起，更何况这仅仅是SG使用云端资源中的一部分。 一些Android端的开源程序尚且可以找酷安这样的相对条件宽松的应用市场分发版本，我们Windows程序又能找谁呢？
> 
> ## 结语
> 我于SG只是一个普通用户，我只是做了点我能做的贡献以表达我对这个项目的喜爱。但我的能力也有限，超过我能力范围的事情我想做也做不到。

您说得对，昨天晚上的时候我确实是说了点气话，这方面的我也没有考虑到
那么，如果我们只需要几个点击就能解决一大堆牵扯到更多钱的问题，又何必让你们额外去花费那个钱呢？
这方面确实是我没有考虑到，抱歉。

**Comment by Lightczx** [comment]
2022.3.2.13 & 2022.3.25.21 由于错误的使用了更新API导致正式通道用户被错误的导向了预览通道 (Github 下载)
下载通道将在下个版本更改
下载体验会在下下个版本改善

**Comment by CzHUV** [comment]
> 2022.3.2.13 & 2022.3.25.21 由于错误的使用了更新API导致正式通道用户被错误的导向了预览通道 (Github 下载) 下载通道将在下个版本更改 下载体验会在下下个版本改善

果然，我猜的就是通道网址弄错了hh

**Comment by scopion** [comment]
白嫖还要求这那的，你脸大？
