### ISSUE TITLE
关于安装切换服务器的插件后出现的一些可手动修改的小问题...

### ISSUE THREAD

**Issue by CzHUV** [DGP-Studio/Snap.Genshin#225]
### Windows 版本

19042.1586

### Snap Genshin 版本

2022 Version 3.25 Build 21

### Snap Genshin 用户设备ID

EA4D2A18959A26C2504A17F061AB272F

### 发生了什么？

在首次启动时，有几率（现不知具体原因）替换失败，导致\$原神安装文件夹$\Genshin Impact Game\ 下的一些文件后缀加上.bak，无法使用
另外，通过\$原神安装文件夹\launcher.exe 重新下载也无法补全文件
这种情况，可以用Everything在\$原神安装文件夹$\Genshin Impact Game\或\$原神安装文件夹 下查找后缀为.bak的文件，并逐个去掉.bak，理论上来说，去掉他们之后重新再切换服务器就好了
请问这是插件出bug还是我的操作失误呢？

### Snap Genshin 用户守则及相关的隐私条款

- [X] 我同意遵守 Snap Genshin 用户守则及相关的隐私条款

**Comment by Lightczx** [comment]
插件的问题不要在这里提，出问题去找插件

**Comment by Lightczx** [comment]
https://github.com/DawnFz/Genshin.Launcher.Plus.SE.Plugin
