### ISSUE TITLE
[feature]: 是否考虑增加成就标记

### ISSUE THREAD

**Issue by AnsuzTrent** [DGP-Studio/Snap.Genshin#230]
### Windows 版本

/

### Snap Genshin 版本

/

### Snap Genshin 用户设备ID

/

### 发生了什么？

https://seelie.inmagi.com/achievements/0

### 你期望发生的行为？

是否考虑增加成就标记功能？

### Snap Genshin 用户守则及相关的隐私条款

- [X] 我同意遵守 Snap Genshin 用户守则及相关的隐私条款

**Comment by Lightczx** [comment]
功能建议不应在此处发表
