### ISSUE TITLE
[Bug]: 重命名自定义网页后，自定义网页的名称变成了空字符串

### ISSUE THREAD

**Issue by ZYFDroid** [DGP-Studio/Snap.Genshin#233]
### Windows 版本

22000.593

### Snap Genshin 版本

3.29 build 74

### Snap Genshin 用户设备ID

null

### 发生了什么？

打开自定义网页选项卡，找到一条，右键选择编辑，然后输入一个新名字，点击保存
网页的名字变成了空白

### 你期望发生的行为？

打开自定义网页选项卡，找到一条，右键选择编辑，然后输入一个新名字，点击保存
**网页的名字能正确显示**

### Snap Genshin 用户守则及相关的隐私条款

- [X] 我同意遵守 Snap Genshin 用户守则及相关的隐私条款

**Comment by Masterain98** [comment]
![Screenshot 2022-03-30 222647](https://user-images.githubusercontent.com/10614984/160982844-e1111d73-86f5-494d-8e8f-015de5019be8.png)

补图
73E268E565E3C93DD066C0C9EBAD4D6F

**Comment by Lightczx** [comment]
fixed
