### ISSUE TITLE
[Bug]: 插件无法启动，武器等级显示为角色等级

### ISSUE THREAD

**Issue by hahayzl** [DGP-Studio/Snap.Genshin#238]
### Windows 版本

19042.631

### Snap Genshin 版本

2022.4.1.18

### Snap Genshin 用户设备ID

1FB7F3E474D94C986120B4230A8549B5

### 发生了什么？

Plugins有插件时无法启动：
#伤害计算器 
[IC.1.0.3.0](https://github.com/DawnFz/SG.Plugin.Injury.Calculator/releases/tag/1.0.3.0)
#国际服支持
[GLP.SE.Plugin.1.0.4.0](https://github.com/DawnFz/Genshin.Launcher.Plus.SE.Plugin/releases/tag/1.0.4.0)

在 工具 - 查询玩家 - 角色信息：
武器等级显示为角色的等级

### Snap Genshin 用户守则及相关的隐私条款

- [X] #240

**Comment by Lightczx** [comment]
插件暂时没有适配新版本
武器等级的问题会在下版本修复

**Comment by Lightczx** [comment]
已知问题，下版本修复
