### ISSUE TITLE
windows11 DGP.Genshin 运行报错

### ISSUE THREAD

**Issue by SunShineJF** [DGP-Studio/Snap.Genshin#24]
windows11 DGP.Genshin 运行报错
系统是从win10升级上来的，win10 程序运行没问题，win11 报错了
[2021-09-15 19-34-11-crash.log](https://github.com/DGP-Studio/Snap.Genshin/files/7169649/2021-09-15.19-34-11-crash.log)
以及 DGP.Genshin.DataViewer 也报错
[snap_genshin_dataviewer_crash.log](https://github.com/DGP-Studio/Snap.Genshin/files/7169660/snap_genshin_dataviewer_crash.log)

**Comment by SunShineJF** [comment]
我电脑C:\Windows\System32中存在urlmon.dll文件

**Comment by Lightczx** [comment]
win11目前是不受支持的操作系统，请等待正式更新

**Comment by Lightczx** [comment]
> 我电脑C:\Windows\System32中存在urlmon.dll文件

64位计算机应该需要在sysWow64内存在urlmon.dll

**Comment by SunShineJF** [comment]
> > 我电脑C:\Windows\System32中存在urlmon.dll文件
> 
> 64位计算机应该需要在sysWow64内存在urlmon.dll

我电脑win11中，sysWow64文件夹中也是有urlmon.dll的。还是等待你们的更新吧~

**Comment by Lightczx** [comment]
能上传一下两个dll文件么，我拿去和win10的对比一下

**Comment by SunShineJF** [comment]
我当前电脑里的[urlmon.zip](https://github.com/DGP-Studio/Snap.Genshin/files/7175700/urlmon.zip)

**Comment by SunShineJF** [comment]
在另一台win10 电脑上，无网络情况下打开，会让绑定米游社cookie，输入cookie后（之前有获取过），程序会闪退。再次打开程序，会出现程序界面，然后立刻闪退。
连网后，打开程序不会闪退，一切正常。
感觉是无网络的时候，在获取米游社数据这里的报错。不是大问题，但还是和你们汇报一下。

**Comment by Lightczx** [comment]
我还没进行过未联网测试。。
我们程序需要联网才能使用大部分功能所以我想不联网应该是极端情况了
当然后面可以做一些是否联网的判断

**Comment by SunShineJF** [comment]
> 能上传一下两个dll文件么，我拿去和win10的对比一下

不好意思，找到原因了，是win11系统的问题。应该是更新过程中出现了问题。
通过 sfc/scannow 命令修复后，程序能打开了。可以正常使用了
麻烦大佬了。。
