### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by kennethyky** [DGP-Studio/Snap.Genshin#241]
### Windows 版本

22581.200

### Snap Genshin 版本

2022.4.1.18

### Snap Genshin 用户设备ID

602E0E8AEC0FB85C85FFED6945C6D501

### 发生了什么？

![image](https://user-images.githubusercontent.com/61400426/161367641-f3feba69-7137-48d1-b323-e190b802d603.png)
插件放入插件文件夹后客户端无法启动

### Snap Genshin 用户守则及相关的隐私条款

- [X] 我同意遵守 Snap Genshin 用户守则及相关的隐私条款

**Comment by Lightczx** [comment]
#238
