### ISSUE TITLE
[Bug]: 客户端页面无法打开（不是缺少框架）

### ISSUE THREAD

**Issue by fengyiZs** [DGP-Studio/Snap.Genshin#242]
### Windows 版本

19044.1620

### Snap Genshin 版本

2022.4.1.18

### Snap Genshin 用户设备ID

59D155BEF299E17CF21A8D9AF4226221

### 发生了什么？

客户端页面无法打开，双击主程序后也没见运行，资源管理器中也没出现相关进程。

### Snap Genshin 用户守则及相关的隐私条款

- [X] 我同意遵守 Snap Genshin 用户守则及相关的隐私条款

**Comment by Lightczx** [comment]
检查框架版本是否匹配

**Comment by fengyiZs** [comment]
> 检查框架版本是否匹配

上个版本还能正常打开，更新之后就打不开了

**Comment by Lightczx** [comment]
#238

**Comment by fengyiZs** [comment]
> #238
OK了，我把插件卸载之后就可以打开了
