### ISSUE TITLE
[Bug]: 静默签到一直无用

### ISSUE THREAD

**Issue by yuanhun** [DGP-Studio/Snap.Genshin#250]
### Windows 版本

18363.418

### Snap Genshin 版本

2022.4.1.18

### Snap Genshin 用户设备ID

40364959450329C95FC308AC28D4C5D4

### 发生了什么？

自从签到功能从设置中心移动账号管理，静默签到直接失效，已经大半个月没修复了。  你们这大半个月更新的新功能我一个都用不上，
但是那个签到弹出的通知，真的让我暴躁的想砸电脑，正好挡着原神的领取奖励，追踪任务按钮，当我追踪3次任务，次次都因为这个签到通知跳到电脑桌面。那时候真的让人狂躁。

### 你期望发生的行为？

我什么都不期望了， 我直接用半个月前的老版本行了吧

### Snap Genshin 用户守则及相关的隐私条款

- [X] 我同意遵守 Snap Genshin 用户守则及相关的隐私条款

**Comment by Lightczx** [comment]
貌似大半个月里也只有你遇到了相关的问题

**Comment by zhouhaixian** [comment]
你遇到问题的心情我们理解，但请你条理清晰、点到为止地报告问题，抱怨并不能帮助我们解决问题，谢谢
