### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by XSANElimos** [DGP-Studio/Snap.Genshin#252]
### Windows 版本

22581.200

### Snap Genshin 版本

2022.3.8.29

### Snap Genshin 用户设备ID

514A2651E6A1615E488C73A96BD1FD7C

### 发生了什么？

【玩家查询】中 查询非自己角色的深渊 无法正常显示使用角色等内容
（很久以前的版本可以 某个版本之后至今最新版本都不行了）

### 你期望发生的行为？

希望可以正常显示深渊使用角色信息

### Snap Genshin 用户守则及相关的隐私条款

- [X] 我同意遵守 Snap Genshin 用户守则及相关的隐私条款

**Comment by XSANElimos** [comment]
![image](https://user-images.githubusercontent.com/58202579/162425262-a627f48b-17de-4a2d-ad28-5186e16affbf.png)
如图所示

**Comment by XSANElimos** [comment]
这是无法修复的是吧？

**Comment by Lightczx** [comment]
米游社限制，无法查询非本人的深渊上场角色
