### ISSUE TITLE
[Bug]: 添加多账号出错

### ISSUE THREAD

**Issue by CzHUV** [DGP-Studio/Snap.Genshin#254]
### Windows 版本

19042.1586

### Snap Genshin 版本

Ver4.7 Build 70

### Snap Genshin 用户设备ID

EA4D2A18959A26C2504A17F061AB272F

### 发生了什么？

当我想要在Snap Genshin上关联多个米游社账号时，最早添加的那个便会无法获取数据
重启后发现，只留下了最新关联的，最早的那个账号消失了
尝试再次添加账号，还是失败，重启后需要重新设置Cookie

### Snap Genshin 用户守则及相关的隐私条款

- [X] 我同意遵守 Snap Genshin 用户守则及相关的隐私条款

**Comment by AdminRoc** [comment]
你好，可以参考此解决方法：

**Comment by CzHUV** [comment]
> 你好，可以参考此解决方法：
> 
> 第一个号直接sg内点击打开新窗口快捷获取，
> 
> 从第二个开始，打开电脑浏览器，并打开无痕模式，按SG内的说明获取cookie，每获取一个账号 就重新打开一次浏览器，并打开无痕模式再获取cookie。
> 
> 为避免其他因素，在这个过程关闭杀软（如果有）
> 
> 补充：如果你的SG是开机自动启动，而你的电脑在开机初期处于没有正常联网的状态，也会导致SG在联网校验cookie有效性的时候验证失败，所以如果你按上述情况获取cookie仍然重启显示账号不全，可以在看到账号失效后尝试立即重启一次sg， 或关闭开机自启，自行在Windows的‘计划任务程序’添加SG的自启，并设置"当前用户登陆&延迟{}分钟启动"的触发条件。 ※关于如何自行添加计划任务的参考教程：https://t.hk.uy/aVya

问题已解决，感谢帮助。
在这里顺便问一下，账号界面的“静默签到”无论开启或是关闭，签到时都会显示在Windows信息栏中，这是个bug吗？

**Comment by AdminRoc** [comment]
will be fixed in later version

**Comment by CzHUV** [comment]
> 

thx
