### ISSUE TITLE
[Bug]: 开启高斯模糊时存在持续异常CPU消耗

### ISSUE THREAD

**Issue by JoshYEn** [DGP-Studio/Snap.Genshin#255]
### Windows 版本

22000.593

### Snap Genshin 版本

4.7 build 70

### Snap Genshin 用户设备ID

554D277198D47D53A3940B7FF59E5711

### 发生了什么？

开启高斯模糊且程序位于前台时，会持续大量占用单核CPU。关闭后恢复正常。

### Snap Genshin 用户守则及相关的隐私条款

- [x] 我同意遵守 Snap Genshin 用户守则及相关的隐私条款

**Comment by JoshYEn** [comment]
不是很容易量化，大约高一倍左右。

**Comment by Lightczx** [comment]
很正常
