### ISSUE TITLE
[Bug]: 2022.4.11.45 养成计算无法正确计算

### ISSUE THREAD

**Issue by TehporP** [DGP-Studio/Snap.Genshin#258]
### Windows 版本

19044.1586

### Snap Genshin 版本

2022.4.11.45

### Snap Genshin 用户设备ID

1938D5E0072645B28BD20B141D61AFEA

### 发生了什么？

在养成计算——我的角色标签下，点击计算按钮无法正确显示所需的物品数量和摩拉数量
在养成计算——所有角色标签下，无论设置起点等级多少，始终是默认初始等级是0
https://sm.ms/image/SRP5rjJQxb9N4De

### 你期望发生的行为？
正确的显示和计算角色所需物品和摩拉数量

### Snap Genshin 用户守则及相关的隐私条款

- [X] 我同意遵守 Snap Genshin 用户守则及相关的隐私条款

**Comment by Lightczx** [comment]
fixed

**Comment by 2190303755** [comment]
> fixed

还是有问题
我的角色 页面
角色 和 武器 的初始等级恒为1
其他的初始等级好像正常
