### ISSUE TITLE
[Bug]: 养成计算中我的角色所有人物和武器初始等级显示问题

### ISSUE THREAD

**Issue by SaooooK1** [DGP-Studio/Snap.Genshin#262]
### Windows 版本

19042.1586

### Snap Genshin 版本

4.13.86

### Snap Genshin 用户设备ID

47FB0F2FD22B35189F7D08119E3CEBD9

### 发生了什么？

养成计算中我的角色所有人物和武器初始等级变成第一个进入时人物和武器登录，不会根据真实情况改变人物和携带武器等级。
![image](https://user-images.githubusercontent.com/103614104/163292831-1d6f95c6-8ee9-4443-942c-456be0b29053.png)
![image](https://user-images.githubusercontent.com/103614104/163292853-567f50ae-670a-4d7a-9395-e833d481c0d0.png)
![image](https://user-images.githubusercontent.com/103614104/163292882-b1baaba3-c671-4b7a-baec-af750e3095f9.png)
![image](https://user-images.githubusercontent.com/103614104/163292906-9fc73031-ffcf-4c97-aeb8-e3aa0b764819.png)

### Snap Genshin 用户守则及相关的隐私条款

- [X] 我同意遵守 Snap Genshin 用户守则及相关的隐私条款

**Comment by Lightczx** [comment]
显示异常，实际计算是正常的

**Comment by SaooooK1** [comment]
计算没反应 就按照这个云堇，正常应该是 20-70，现在70-70点计算是计算不出东西

**Comment by SaooooK1** [comment]
默认不行，要手动修改下最大等级就能计算。。。

**Comment by Lightczx** [comment]
已经修复了，请耐心等待下版本发布
