### ISSUE TITLE
[Bug]: 静默签到修好了，自动签到又不中用了

### ISSUE THREAD

**Issue by CzHUV** [DGP-Studio/Snap.Genshin#263]
### Windows 版本

19042.1645

### Snap Genshin 版本

Ver4.14 Build 95

### Snap Genshin 用户设备ID

EA4D2A18959A26C2504A17F061AB272F

### 发生了什么？

如题，更新后静默签到有效了，可是又不能自动签到了（选项已勾选）

### Snap Genshin 用户守则及相关的隐私条款

- [X] 我同意遵守 Snap Genshin 用户守则及相关的隐私条款

**Comment by CzHUV** [comment]
补充一句，我是在多账号关联模式下自动签到失效的

**Comment by Lightczx** [comment]
手动点击自动签到有效么

**Comment by CzHUV** [comment]
> 手动点击全部签到有效么
有效

**Comment by Lightczx** [comment]
> > 手动点击全部签到有效么
> > 有效

那应该是初始化的问题，会在下版本修复

**Comment by Lightczx** [comment]
后台没有收到你的任何报错信息，可以肯定的是签到操作是100%执行了的

**Comment by Lightczx** [comment]
自动签到已经确定是我们的代码的问题，目前只有UTC+8 08:00 前签到成功才能正常
会在下版本修复

**Comment by CzHUV** [comment]
thx
