### ISSUE TITLE
[Bug]: 角色养成页面,装备降临之剑的角色无法显示武器

### ISSUE THREAD

**Issue by candywzt** [DGP-Studio/Snap.Genshin#264]
### Windows 版本

22563

### Snap Genshin 版本

2022.4.14.95

### Snap Genshin 用户设备ID

E373BF42728F4ABD2E21353D80CA54BE

### 发生了什么？

养成计算页面，我的角色，装备降临之剑的角色无法显示武器，会显示上一次点开的角色装备的武器图标
[![Lt0CGT.png](https://s1.ax1x.com/2022/04/16/Lt0CGT.png)](https://imgtu.com/i/Lt0CGT)

### Snap Genshin 用户守则及相关的隐私条款

- [X] 我同意遵守 Snap Genshin 用户守则及相关的隐私条款

**Comment by Lightczx** [comment]
米游社的限制，确实无法计算
