### ISSUE TITLE
[Bug]: 更新后无法正常打开，打开后持续停留在“等待网络连接...”页面

### ISSUE THREAD

**Issue by bApJQK** [DGP-Studio/Snap.Genshin#271]
### Windows 版本

19043.1645

### Snap Genshin 版本

2022.4.17.16

### Snap Genshin 用户设备ID

无法进入程序，无法查看

### 发生了什么？

今天打开程序自动更新后，再次打开就会一直停留在“等待网络连接...”，在今天未更新之前我都能正常打开使用。 ps.我的网络是正常连接的。网页，游戏都能正常打开。

### Snap Genshin 用户守则及相关的隐私条款

- [X] 我同意遵守 Snap Genshin 用户守则及相关的隐私条款

**Comment by Lightczx** [comment]
ping api-takumi.mihoyo.com

**Comment by bApJQK** [comment]
请求超时，可能是我自己的问题了:(
