### ISSUE TITLE
[Bug]: 使用启动器功能直接黑屏

### ISSUE THREAD

**Issue by zhouyanyu** [DGP-Studio/Snap.Genshin#273]
### Windows 版本

22000.613

### Snap Genshin 版本

2020.3.23

### Snap Genshin 用户设备ID

D0993D151B964C9DB8B1CFBBEEA61C11

### 发生了什么？

我使用启动器功能直接黑屏

### Snap Genshin 用户守则及相关的隐私条款

- [X] 我同意遵守 Snap Genshin 用户守则及相关的隐私条款

**Comment by AdminRoc** [comment]
您好，因为您已经多天未提交进一步的信息，并且目前暂无同类反馈出现，所以本issue暂时关闭
反馈专用群：https://jq.qq.com/?_wv=1027&k=ufUJMSxP
