### ISSUE TITLE
[Bug]: 角色资料 界面，快速切换可能导致角色技能串图标

### ISSUE THREAD

**Issue by LiuWTQAQ** [DGP-Studio/Snap.Genshin#274]
### Windows 版本

19043.1679

### Snap Genshin 版本

Ver 4.25 Build60

### Snap Genshin 用户设备ID

887638E2DD21C660A669A14A12512E8F

### 发生了什么？

![image](https://user-images.githubusercontent.com/104381006/165135194-ae7c98b5-e561-4ad1-9bb3-53fb051d2829.png)
在“角色资料”界面，快速切换可能导致角色技能串图标

### Snap Genshin 用户守则及相关的隐私条款

- [X] 我同意遵守 Snap Genshin 用户守则及相关的隐私条款

**Comment by Lightczx** [comment]
首次缓存技能命座等图标会有这个问题
在缓存好后就不会有这个问题了

**Comment by LiuWTQAQ** [comment]
问题是角色的技能也是串的，阿贝多是射箭的吗？（doge）

**Comment by Lightczx** [comment]
文字描述是匹配的
