### ISSUE TITLE
[Bug]: 有插件无法启动

### ISSUE THREAD

**Issue by Winter-is-comingXK** [DGP-Studio/Snap.Genshin#275]
### Windows 版本

19044.1620

### Snap Genshin 版本

4.25 Build 60

### Snap Genshin 用户设备ID

967B9A419873D5C9D299DB6E569D4805

### 发生了什么？

在插件目录下放入插件后，软件无法启动
删除插件后即可启动
插件为 `Injury.Calculator.Plugin.dll` 

### 你期望发生的行为？

正常启动

### Snap Genshin 用户守则及相关的隐私条款

- [X] 我同意遵守 Snap Genshin 用户守则及相关的隐私条款

**Comment by AdminRoc** [comment]
除部分特殊插件(SG开发者自己编写的)外，群文件插件都是热心用户自己写的。
由于有的作者没有在SG更新之后，按情况更新自己的作品(插件)，所以在某一新版本可能就会出现插件无效或者SG打不开的情况，与SG无关，所以不在反馈问题的范畴内。 
解决方式： 
①：请咨询插件作者（在插件管理内有显示）。 
②：直接删除您自己放入SnapGenshin文件夹内的Plugins文件夹的该插件(*.dll)文件。
