### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by juychen** [DGP-Studio/Snap.Genshin#278]
### Windows 版本

22000.613

### Snap Genshin 版本

2022.4.25.60

### Snap Genshin 用户设备ID

DB667787C763955EDB20310E019258E8

### 发生了什么？

提示更新元数据失败。

### Snap Genshin 用户守则及相关的隐私条款

- [X] 我同意遵守 Snap Genshin 用户守则及相关的隐私条款

**Comment by AdminRoc** [comment]
您好，可以此目录下所有文件下载一份放到自己Snapgenshin文件夹内的 (Metadata) 文件夹，再重启SG查看是否恢复 https://resource.snapgenshin.com/Metadata2/

![image](https://user-images.githubusercontent.com/96916320/165755330-64b989cc-5dd9-443f-b290-965033742d55.png)
