### ISSUE TITLE
[Bug]: 钟离命之座显示问号

### ISSUE THREAD

**Issue by soulgazor** [DGP-Studio/Snap.Genshin#279]
### Windows 版本

win10 版本2009（OS内部版本 19042.1526）

### Snap Genshin 版本

2022-Version 4.26 Build 77

### Snap Genshin 用户设备ID

7CA924FBFE422303513C4C289CD3F48E

### 发生了什么？

角色资料模块，查看钟离信息，命之座显示为“？？？”

### 你期望发生的行为？

正常应该显示是岩王帝君座

### Snap Genshin 用户守则及相关的隐私条款

- [X] 我同意遵守 Snap Genshin 用户守则及相关的隐私条款

**Comment by AdminRoc** [comment]
你好，可以尝试将SnapGenshin所在的文件夹内的“cache”文件夹清空，再重启SnapGenshin查看是否恢复正常。

**Comment by soulgazor** [comment]
> 你好，可以尝试将SnapGenshin所在的文件夹内的“cache”文件夹清空，再重启SnapGenshin查看是否恢复正常。

刚试了下，并没有变化

**Comment by soulgazor** [comment]
> 你好，可以尝试将SnapGenshin所在的文件夹内的“cache”文件夹清空，再重启SnapGenshin查看是否恢复正常。

我查了一下，问题是在`Snap.Genshin\Metadata\characters.json`中，钟离的命座描述信息就是问号
参考这几张图
[](https://www.helloimg.com/images/2022/04/29/RM7Yf9.md.jpg)
[](https://www.helloimg.com/images/2022/04/29/RM7hqX.md.jpg)

**Comment by AdminRoc** [comment]
经确认，钟离在完成传说任务之前，实际的显示就是问号
![image](https://user-images.githubusercontent.com/96916320/165873097-e04bee8d-1892-4105-b47e-5e85ae6599d7.png)
