### ISSUE TITLE
[Bug]: 启动时在等待界面无限等待无法进入

### ISSUE THREAD

**Issue by FengYuechen** [DGP-Studio/Snap.Genshin#284]
### Windows 版本

19044.1645

### Snap Genshin 版本

2022.4.28.7

### Snap Genshin 用户设备ID

由于无法进入程序而不能填写

### 发生了什么？

![image](https://user-images.githubusercontent.com/70253113/166150174-b419624e-946d-4b63-a6e7-96e1373cc8dd.png)

### Snap Genshin 用户守则及相关的隐私条款

- [X] 我同意遵守 Snap Genshin 用户守则及相关的隐私条款

**Comment by FengYuechen** [comment]
![image](https://user-images.githubusercontent.com/70253113/166150307-daec4ef1-1e62-4c65-a54e-9a26ff10587a.png)

**Comment by AdminRoc** [comment]
1.关闭电脑中的网络代理
2.给出粗暴的解决方法：解压此文件覆盖Snapgenshin的文件夹。
临时链接：https://www.wenshushu.cn/f/87o1vdfmnkd
