### ISSUE TITLE
[Bug]: 更新元数据失败

### ISSUE THREAD

**Issue by lattefish** [DGP-Studio/Snap.Genshin#285]
### Windows 版本

win10 20H2

### Snap Genshin 版本

5.4日发布的最新版本

### Snap Genshin 用户设备ID

无法打开查询不到

### 发生了什么？

旧版本更新后打不开，系统提示更新元数据失败，程序卡在 检验缓存资源完整性 这里，把整个程序文件夹全删了重新安装还是一样的问题，后来把Microsoft.WindowsDesktop.App 6.0.2 更新到 6.0.4后还是不行

### Snap Genshin 用户守则及相关的隐私条款

- [X] 我同意遵守 Snap Genshin 用户守则及相关的隐私条款

**Comment by Masterain98** [comment]
下载缓存文件试试
[https://resource.snapgenshin.com/Cache.zip](https://resource.snapgenshin.com/Cache.zip)
