### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by QyInvoLing** [DGP-Studio/Snap.Genshin#288]
### Windows 版本

22000.613

### Snap Genshin 版本

2022 v5.5 b13

### Snap Genshin 用户设备ID

7ED4A272FAC8A09BDE5116A83E4E2B65

### 发生了什么？

启动器存在时，关闭Windows提示“这个应用阻止关机”

### 你期望发生的行为？

snap genshin 不阻碍关机

### Snap Genshin 用户守则及相关的隐私条款

- [X] 我同意遵守 Snap Genshin 用户守则及相关的隐私条款

**Comment by Lightczx** [comment]
刻意的设计
