### ISSUE TITLE
[Bug]: 账号管理出错

### ISSUE THREAD

**Issue by anpoz** [DGP-Studio/Snap.Genshin#290]
### Windows 版本

22000.675

### Snap Genshin 版本

2022.5.5.13

### Snap Genshin 用户设备ID

E0238BE05E5071D48B78227BC23443A8

### 发生了什么？

也许是之前填写的cookie有在米哈游官网上有过退出登录行为，结果出现了如下图的情况。即便是重新登录页面获取新的cookie，再在应用里重新添加也不能恢复正常，而且也不能删除该账号重新添加
![屏幕截图 2022-05-13 193124](https://user-images.githubusercontent.com/2825342/168275178-9a0f7d9e-a4a5-428b-bd9a-52a482e066aa.jpg)

### 你期望发生的行为？

期望在发生cookie过期或者无法使用时，能提供恢复手段，例如重新填写之类的

### Snap Genshin 用户守则及相关的隐私条款

- [X] 我同意遵守 Snap Genshin 用户守则及相关的隐私条款

**Comment by Tolvydas1** [comment]
救命我也出现了这种问题 不知道怎么解决

**Comment by AdminRoc** [comment]
出现了cookie识别不了的情况，立即重启SG就行，如果这种情况点击了获取cookie，之前的cookie自然就没了

> 救命我也出现了这种问题 不知道怎么解决
