### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Ba-Bao-zhou** [DGP-Studio/Snap.Genshin#293]
### Windows 版本

Windows 7 旗舰版

### Snap Genshin 版本

2022-verison 4.7 Build70

### Snap Genshin 用户设备ID

33E14F25CD3A7CAA256A75C304BCA51A

### 发生了什么？

玩家查询-角色信息：武器精炼信息混乱

### 你期望发生的行为？

分别显示武器突破等级和武器精炼等级

### Snap Genshin 用户守则及相关的隐私条款

- [X] 我同意遵守 Snap Genshin 用户守则及相关的隐私条款

**Comment by Lightczx** [comment]
更新
