### ISSUE TITLE
[Bug]: 国际服转换国服客户端之后无法启动游戏

### ISSUE THREAD

**Issue by ilovinht** [DGP-Studio/Snap.Genshin#295]
### Windows 版本

19044.1706

### Snap Genshin 版本

5.5

### Snap Genshin 用户设备ID

A1F4D929DDDAF44B300D885C02D92D65

### 发生了什么？

用的国际服客户端，转换成国服之后启动游戏的那个exe文件名会变成yuanshen.exe，但是它似乎还在找原来的genshinimpact.exe？
![QQ截图20220528213000](https://user-images.githubusercontent.com/54866918/170825714-8620fa11-9631-4d32-bd36-daa74cacab74.png)

### 你期望发生的行为？

转换之后点击启动游戏可以正常启动游戏

### Snap Genshin 用户守则及相关的隐私条款

- [X] 我同意遵守 Snap Genshin 用户守则及相关的隐私条款

**Comment by Lightczx** [comment]
插件问题与本体无关
