### ISSUE TITLE
[Bug]: 养成计算器没有显示

### ISSUE THREAD

**Issue by bgGuo** [DGP-Studio/Snap.Genshin#301]
### Windows 版本

19044.1706

### Snap Genshin 版本

version 5.31 build93

### Snap Genshin 用户设备ID

7C798F2392C38B2ECB95A8D1F2F3669E

### 发生了什么？

![image](https://user-images.githubusercontent.com/106642690/171321528-b118f21c-2242-4f48-a58b-fd16ccfa149e.png)
![image](https://user-images.githubusercontent.com/106642690/171321573-c39c7a19-c7e7-4edc-aced-d77999ac345a.png)
![image](https://user-images.githubusercontent.com/106642690/171321608-ca5b72bd-493a-43e6-b161-952ca5099d65.png)

### Snap Genshin 用户守则及相关的隐私条款

- [X] 我同意遵守 Snap Genshin 用户守则及相关的隐私条款

**Comment by AdminRoc** [comment]
请更新到最新版本。即## Version 7.6 Build 14 ##
