### ISSUE TITLE
[Bug]: 不同分辨率的多显示器下窗口尺寸问题

### ISSUE THREAD

**Issue by JingAnTony** [DGP-Studio/Snap.Genshin#304]
### Windows 版本

22000.675

### Snap Genshin 版本

V5.31 Build 53

### Snap Genshin 用户设备ID

491902921C50AC94D8C38C3416D46450

### 发生了什么？

使用双显示器（扩展模式，分辨率不同）且分辨率较低的显示器为主显示器时，在分辨率较大的显示器上打开程序后关闭窗口并置于后台，再次打开程序（或使用管理员模式重启）时窗口会变得过大且无法拖动。每次均可复现。

临时解决方法：将显示器设置为仅高分辨率显示器显示，重新打开软件，调小窗口尺寸，切回扩展模式，大概率可恢复正常。

配置情况：
显示器1（副）：4k 60Hz
显示器2（主）：2k 165Hz
CPU：AMD 5900X
显示卡：AMD 6900XT

### 你期望发生的行为？

再次打开时窗口应置于原显示器原位置，或根据分辨率按比例调整窗口大小。

### Snap Genshin 用户守则及相关的隐私条款

- [X] 我同意遵守 Snap Genshin 用户守则及相关的隐私条款

**Comment by Lightczx** [comment]
打开时的位置取决于你鼠标在打开时的屏幕
只要保证鼠标与上次关闭窗口时位置相同
就可以避免这个问题

**Comment by Lightczx** [comment]
如果想要拖动窗口，可以寻找窗口的任意边框，调整后会自动缩小到屏幕大小以内
