### ISSUE TITLE
[Bug]: 官服和B服的切换是不是不能用了？

### ISSUE THREAD

**Issue by TRIEYES** [DGP-Studio/Snap.Genshin#308]
### Windows 版本

22621.1

### Snap Genshin 版本

2022.5.31.93

### Snap Genshin 用户设备ID

8B319DCE3284B15E03EC778C0CAA21AE

### 发生了什么？

B服的SDK放在对应位置后，提示备份 bilibili SDK 失败，装换可能不会生效。

### Snap Genshin 用户守则及相关的隐私条款

- [x] 我同意遵守 Snap Genshin 用户守则及相关的隐私条款

**Comment by TRIEYES** [comment]
2.6的时候是正常的，2.7更新后才不行的。看其他的一些同类工具说是2.7版本的启动器有修改

**Comment by SImaHongcai** [comment]
> 2.6的时候是正常的，2.7更新后才不行的。看其他的一些同类工具说是2.7版本的启动器有修改

事实上2.7更新之后也是可用的，用完还能切回来。
![QQ图片20220606230625](https://user-images.githubusercontent.com/92454987/172188561-888b6f9e-4f05-4fc2-bff2-bacbf1a5743a.png)

**Comment by Lightczx** [comment]
2.7 的SDK有更新

**Comment by SImaHongcai** [comment]
> 2.7 的SDK有更新

我在你的网站下载的sdk_pkg_version文件的修改日期是2022‎年‎3‎月‎24‎日，‏‎15:41:57，PCGameSDK.dll文件的修改日期是2022-03-24 15:41:57，仍然实现了官B服的切换。
