### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by AlbertWen-AW** [DGP-Studio/Snap.Genshin#310]
### Windows 版本

Win 10 21H2  (19044.1706)

### Snap Genshin 版本

Snap Genshin 2022 - version 5.31 Build 93

### Snap Genshin 用户设备ID

241AF3BC21C6D5F57C2B594AA38A4732

### 发生了什么？

成就统计中没有2.7新增的6个成就：3个 天地万象魔神任务间章第二章的隐藏成就（游戏内已开放获取）游戏内已开放获取) 和 3个 久岐忍邀约任务成就（未开放获取）
并且导入椰羊的文件后软件崩溃

### 你期望发生的行为？

成就统计中添加2.7的成就并且修复上述问题
感谢各位开发者

### 相关的崩溃日志

```shell
没有找到/弹出崩溃日志
```

### Snap Genshin 用户守则及相关的隐私条款

- [x] 我同意遵守 Snap Genshin 用户守则及相关的隐私条款

**Comment by Lightczx** [comment]
位置-更新元数据
