### ISSUE TITLE
无法兼容 genshin-wish-export导出的2.1版本的uigf

### ISSUE THREAD

**Issue by summer-breeze123** [DGP-Studio/Snap.Genshin#313]
### Windows 版本

19043.1165

### Snap Genshin 版本

6.8

### Snap Genshin 用户设备ID

77A3BA5A2C06DCEC20B39E426EAC66E2

### 发生了什么？

无法兼容 genshin-wish-export导出的2.1版本的uigf
或者说是不再支持低版本的？

### Snap Genshin 用户守则及相关的隐私条款

- [X] 我同意遵守 Snap Genshin 用户守则及相关的隐私条款

**Comment by Lightczx** [comment]
json文件发一下

**Comment by summer-breeze123** [comment]
> json文件发一下

不太会用GitHub，发邮件了

**Comment by Lightczx** [comment]
没收到

**Comment by Lightczx** [comment]
gwe需要0.8.2版本以上导出

**Comment by summer-breeze123** [comment]
> gwe需要0.8.2版本以上导出

但是gwe没有0.8.2版本，最新只有0.8.1

**Comment by Lightczx** [comment]
> > gwe需要0.8.2版本以上导出
> 
> 但是gwe没有0.8.2版本，最新只有0.8.1

有，自己想办法更新

**Comment by summer-breeze123** [comment]
> > > gwe需要0.8.2版本以上导出
> > 
> > 
> > 但是gwe没有0.8.2版本，最新只有0.8.1
> 
> 有，自己想办法更新

行吧，我自己想办法
