### ISSUE TITLE
部分角色资料立绘显示异常[Bug]: 

### ISSUE THREAD

**Issue by DavidLWB** [DGP-Studio/Snap.Genshin#320]
### Windows 版本

19043.1706

### Snap Genshin 版本

2022。6.8.27

### Snap Genshin 用户设备ID

66C575AB20F83F390B17ACABA29BBBB6

### 发生了什么？

部分角色资料立绘显示异常，会显示上一个加载的角色立绘

### Snap Genshin 用户守则及相关的隐私条款

- [X] 我同意遵守 Snap Genshin 用户守则及相关的隐私条款

**Comment by Lightczx** [comment]
耐心等待
