### ISSUE TITLE
打不开，解压publish后双击启动就没反应了

### ISSUE THREAD

**Issue by juju0708** [DGP-Studio/Snap.Genshin#327]
### Windows 版本

.

### Snap Genshin 版本

.

### Snap Genshin 用户设备ID

.

### 发生了什么？

rt

### Snap Genshin 用户守则及相关的隐私条款

- [X] 我同意遵守 Snap Genshin 用户守则及相关的隐私条款

**Comment by Masterain98** [comment]
请阅读官方文档的常见问题一节
