### ISSUE TITLE
希望增加 旅行者扎记 的记录

### ISSUE THREAD

**Issue by molehzy** [DGP-Studio/Snap.Genshin#33]
https://hk4e-api.mihoyo.com/event/ys_ledger/monthDetail?page=(页数)&month=(月份，仅支持查询近三个月)&limit=(一次的返回信息数量)&type=(1为原石,2为摩拉)&bind_uid=(游戏ID)&bind_region=(所在服)
cookie需要cookie_token和account_id
![](https://raw.githubusercontent.com/molehzy/molehzy.github.io/master/img/issues/issues01.jpg)

**Comment by Lightczx** [comment]
我们在很早之前就做好了相关的页面，但直到目前该页面仍处于仅开发人员可见状态
目前仍处于UI开发阶段
**如果想要提前体验可以在`settings.json`中将 *IsDevMode* 项设为true后启动，并切换到旅行札记页面**

**Comment by Lightczx** [comment]
最近开发的比较繁忙了，ToDo List 会在空下来的时候加上
