### ISSUE TITLE
[Bug]: 其中一个账号无法拉取体力等信息

### ISSUE THREAD

**Issue by root0day** [DGP-Studio/Snap.Genshin#337]
### Windows 版本

win10 ltsc  - Windows 10 1809 

### Snap Genshin 版本

Snap Genshin 2022 Version 6.22 Build 41

### Snap Genshin 用户设备ID

0A2AF7D4D7F99E0FE3F71443E92BE9BE

### 发生了什么？

反馈一个BUG  在添加完账号后  不知道为啥  其中一个账号F无法获取到树脂等信息  其他账号正常获取树脂信息(且能正常刷新)
我删除这个账号用隐身模式登录后重新获取cookie添加 也不能显示树脂信息

这就是那个不正常的号
![image](https://user-images.githubusercontent.com/26130494/177436505-d8e06ba6-e21a-412d-8ec0-46f2db563c04.png)

此次是正常账号的
![image](https://user-images.githubusercontent.com/26130494/177436516-1f5d4650-065e-4b59-92da-b6f21d47780b.png)

怀疑是否是snmp genshin本地缓存问题?

### Snap Genshin 用户守则及相关的隐私条款

- [X] 我同意遵守 Snap Genshin 用户守则及相关的隐私条款

**Comment by Lightczx** [comment]
米游社里面看一下
