### ISSUE TITLE
[Bug]: 胡桃数据库无法上传个人数据

### ISSUE THREAD

**Issue by john9999911** [DGP-Studio/Snap.Genshin#338]
### Windows 版本

win10 21H2

### Snap Genshin 版本

v5.29 build 24

### Snap Genshin 用户设备ID

7170B5593A674C1AAA9766C69D878F12

### 发生了什么？

![image](https://user-images.githubusercontent.com/80616586/177478397-88a0809b-aef7-4ac4-ae8e-66e213680ac4.png)

### Snap Genshin 用户守则及相关的隐私条款

- [X] 我同意遵守 Snap Genshin 用户守则及相关的隐私条款

**Comment by Masterain98** [comment]
升级主程序至最新版本
