### ISSUE TITLE
[Bug]: 2.8版本更新后进不了游戏

### ISSUE THREAD

**Issue by joker4224** [DGP-Studio/Snap.Genshin#343]
### Windows 版本

19044.1766

### Snap Genshin 版本

2022 version4.1 build18

### Snap Genshin 用户设备ID

9793A46D41397B06C3660E91EA7C6711

### 发生了什么？

更新前服务器选择的是 "官方服 | 天空岛"，通过官方启动器更新后服务器选择变为“渠道服 | 世界树”，导致进不了游戏，提示二级地址解析失败。重新选择 "官方服 | 天空岛" 后正常。
![G~(4DE SU_1 PHE(_WWN`QX](https://user-images.githubusercontent.com/49227645/178725835-9ea7d489-a0b5-4509-94f1-efb3e6183f14.png)

### 你期望发生的行为？

更新后正确判断游戏服务器。

### Snap Genshin 用户守则及相关的隐私条款

- [X] 我同意遵守 Snap Genshin 用户守则及相关的隐私条款

**Comment by AdminRoc** [comment]
“通过官方启动器更新后服务器选择变为‘渠道服 | 世界树’，导致进不了游戏”

**Comment by Lightczx** [comment]
bili的sdk应该要更新了
