### ISSUE TITLE
[Bug]: 大保底不显示up

### ISSUE THREAD

**Issue by helishou** [DGP-Studio/Snap.Genshin#346]
### Windows 版本

v7.8 build 48

### Snap Genshin 版本

build 7.8

### Snap Genshin 用户设备ID

FB645F8CE5E3A5935A240D7FD2083138

### 发生了什么？

![image](https://user-images.githubusercontent.com/41136716/179375882-202d3828-4115-47f1-859f-11dec2699922.png)

### 你期望发生的行为？

应该标识Up

### 相关的崩溃日志

```shell
无11
```

### Snap Genshin 用户守则及相关的隐私条款

- [X] 我同意遵守 Snap Genshin 用户守则及相关的隐私条款

**Comment by Lightczx** [comment]
更新元数据
