### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Yuang520** [DGP-Studio/Snap.Genshin#347]
### Windows 版本

22000.795

### Snap Genshin 版本

Snap Genshin 2022 - Version 7.8 Build 48

### Snap Genshin 用户设备ID

B01337916FBAAF9802D7DAE18FA8DCC4

### 发生了什么？

在使用成就导入软件YaeAchievement时，当Snap Genshin处于成就页面时，会出现成就导入失败的问题

### Snap Genshin 用户守则及相关的隐私条款

- [X] 我同意遵守 Snap Genshin 用户守则及相关的隐私条款

**Comment by Lightczx** [comment]
SG的设计就是如此，不可避免
请等待SH实现该功能
