### ISSUE TITLE
[Bug]: 无法获取国际版抽卡记录

### ISSUE THREAD

**Issue by Canary233** [DGP-Studio/Snap.Genshin#353]
### Windows 版本

22000.795

### Snap Genshin 版本

7.24 Build 10000

### Snap Genshin 用户设备ID

D4A9E7FB24471C57385B72D463B2B6F2

### 发生了什么？

抽卡记录从日志获取失败，按照提示打开抽卡历史记录并刷新也无效。
手动输入url提示 可能是验证密钥已过期，但使用https://wwe.lanzoux.com/b010bstsd密码:muknb导入可以正常获取 

### Snap Genshin 用户守则及相关的隐私条款

- [X] 我同意遵守 Snap Genshin 用户守则及相关的隐私条款

**Comment by Masterain98** [comment]
Snap Genshin 目前不支持国际服抽卡记录保存
