### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by xiaolongqq1y** [DGP-Studio/Snap.Genshin#356]
### Windows 版本

25158.1000

### Snap Genshin 版本

2022.7.24.10000

### Snap Genshin 用户设备ID

E6C92143CA96D39B1897A1DD75B43B53

### 发生了什么？

打开养成计算中的所有武器会闪退

### Snap Genshin 用户守则及相关的隐私条款

- [X] 我同意遵守 Snap Genshin 用户守则及相关的隐私条款

**Comment by Lightczx** [comment]
删除Cache
