### ISSUE TITLE
不能从execl导入抽卡记录吗

### ISSUE THREAD

**Issue by keyminori** [DGP-Studio/Snap.Genshin#36]
sunfkny/genshin-gacha-export 
原神现在无法加载6个月前的记录
这个如果第一次用的话没法把以前的老记录合并
导致记录不全

Scighost/KeqingNiuza
牛杂店也不能导入老数据

biuuu/genshin-wish-export
这个能用execl导入老记录
但是json不通用

目前几个统计工具导出的excel基本差不多
但是json就不太一样

**Comment by Lightczx** [comment]
外部导入数据需要满足每条数据中包含id（TimeId）,目前只有sunfkny的gge包含，所以只能从他的项目导入

**Comment by Aniverse** [comment]
Scighost/KeqingNiuza 是可以导入 biuuu/genshin-gacha-export 的 excel 的，在关于界面里
另外牛杂店是有祈愿 Id 的，应该就是 TimeId 吧
