### ISSUE TITLE
[Bug]: 无法兼容2.1版本的uigf.json

### ISSUE THREAD

**Issue by So1nata** [DGP-Studio/Snap.Genshin#360]
### Windows 版本

22000.795

### Snap Genshin 版本

2022.7.24.10000

### Snap Genshin 用户设备ID

54B11219262AB36EE6482893CCC90223

### 发生了什么？

无法兼容 genshin-wish-export0.8.2版本导出的2.1版本的uigf，
在[https://www.snapgenshin.com/development/UIGF.html#info](url)中可以查看是可以向下兼容的。
附件zip为2.1版本的json
[UIGF_500781240_2022831343.zip](https://github.com/DGP-Studio/Snap.Genshin/files/9249062/UIGF_500781240_2022831343.zip)
。

### Snap Genshin 用户守则及相关的隐私条款

- [X] 我同意遵守 Snap Genshin 用户守则及相关的隐私条款

**Comment by Lightczx** [comment]
经过测试没有问题
