### ISSUE TITLE
[Bug]: 软件在托盘的时候如果点击软件打开的话会没有反应而不是像微信那种直接跳跳出来

### ISSUE THREAD

**Issue by long45343** [DGP-Studio/Snap.Genshin#361]
### Windows 版本

22621.450

### Snap Genshin 版本

2022 version7.24 build 10000

### Snap Genshin 用户设备ID

B2BE607EE889F23093F9EEA6D83CAFCE

### 发生了什么？

应用程序在托盘的时候如果从开始菜单启动的话不会有反应，且没有提示

### 你期望发生的行为？

当应用在托盘的时候再打开应用的时候让应用界面显示出来或者给一个"该应用已打开"的提示

### Snap Genshin 用户守则及相关的隐私条款

- [X] 我同意遵守 Snap Genshin 用户守则及相关的隐私条款

**Comment by Lightczx** [comment]
处于托盘时启动新进程会打开主窗体的
