### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by abandonstudy** [DGP-Studio/Snap.Genshin#363]
### Windows 版本

22000.795

### Snap Genshin 版本

2022.8.5.11317

### Snap Genshin 用户设备ID

FD957834C8D9035EF758401DABF6E92C

### 发生了什么？

角色橱窗查询中输入111111111（我确定有这个人)后闪退
输入我自己的UID时正常
视频链接： https://weiziyu-my.sharepoint.com/:v:/g/personal/test_weiziyu_onmicrosoft_com/EVwpwX1_--lDhUktUTwd2esBUUe1cgBKupMuaCIHp_UrIw?e=tAuwNG
(太大了传不了GitHub）
![image](https://user-images.githubusercontent.com/94209629/183036791-4f0338ac-4702-4875-9b11-3e547b3241ed.png)

### 你期望发生的行为？

成功查询角色橱窗

### 相关的崩溃日志

```shell
大部分情况下只有个崩溃窗口，一片白
有一次日志文件显示了1s内容就没了
```

### Snap Genshin 用户守则及相关的隐私条款

- [X] 我同意遵守 Snap Genshin 用户守则及相关的隐私条款

**Comment by Masterain98** [comment]
来一群群文件来下载一个 `Cache.zip` 解压覆盖

**Comment by abandonstudy** [comment]
> 来一群群文件来下载一个 解压覆盖`Cache.zip`

经过尝试，此方法无效

**Comment by AdminRoc** [comment]
> 

打开链接下载，覆盖现在SG的文件夹：https://hz7163.apps.aliyunpds.com/s/vqieKihj7A4

**Comment by abandonstudy** [comment]
下载完群主的cache文件后问题解决了，谢谢各位大佬
