### ISSUE TITLE
[Bug]: 打开wiki下任意一栏出现闪退

### ISSUE THREAD

**Issue by lessforname** [DGP-Studio/Snap.Genshin#369]
### Windows 版本

19044.1826

### Snap Genshin 版本

2022 8.6 build 29506

### Snap Genshin 用户设备ID

EA39781DAD67A48F80C9D27629B6C743

### 发生了什么？

点击wiki下任意一栏在加载后发生闪退

### 你期望发生的行为？

能正常打开

### Snap Genshin 用户守则及相关的隐私条款

- [X] 我同意遵守 Snap Genshin 用户守则及相关的隐私条款

**Comment by Lightczx** [comment]
#363
