### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Aquan666** [DGP-Studio/Snap.Genshin#370]
### Windows 版本

19044.1826

### Snap Genshin 版本

Version 8.6 Build 29506

### Snap Genshin 用户设备ID

28D5AE2C24615DB8DCB71C1BB9F64E7D

### 发生了什么？

打开角色资料时崩溃

### Snap Genshin 用户守则及相关的隐私条款

- [X] 我同意遵守 Snap Genshin 用户守则及相关的隐私条款

**Comment by Lightczx** [comment]
#363
