### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by miku0712** [DGP-Studio/Snap.Genshin#371]
### Windows 版本

22000.795

### Snap Genshin 版本

2022.8.6.29506

### Snap Genshin 用户设备ID

3D39A64D9E29AA7DCB6778A95940B702

### 发生了什么？

①点击 角色资料 点开除万叶外的角色程序弹出个新白窗口然后直接崩溃，其余功能正常使用。
②重装后点击 设置 里缓存角色资源后点击角色资料、日常、周常材料、武器资料全崩溃。
③清空图片缓存文件夹后返回①状态。
④最开始 点击 设置 里 缓存角色资源 后出现问题。
⑤复制别人缓存文件替代同①情况。
文件大于25MB无法上传
https://pan.baidu.com/s/1q2UnSezZoMjN-ez5h-fQzQ
提取码：1234

### 相关的崩溃日志

```shell
直接崩溃
```

### Snap Genshin 用户守则及相关的隐私条款

- [X] 我同意遵守 Snap Genshin 用户守则及相关的隐私条款

**Comment by Lightczx** [comment]
#363

**Comment by miku0712** [comment]
下载群文件 Cache 成功解决
😍
