### ISSUE TITLE
[Bug]: 使用SnapGenshin启动游戏后无法被OBS捕获

### ISSUE THREAD

**Issue by hoiyuyiu** [DGP-Studio/Snap.Genshin#372]
### Windows 版本

22621.382

### Snap Genshin 版本

Version 8.11 Build 44373

### Snap Genshin 用户设备ID

602E0E8AEC0FB85C85FFED6945C6D501

### 发生了什么？

无论是否开启帧率解锁，使用SnapGenshin直接启动游戏均无法被OBS的“游戏源”捕获，会卡在某一界面，然后丢失画面（如图），再次从SnapGenshin启动则会直接无法捕获；如果直接从游戏目录下启动yuanshen.exe则可正常被OBS“游戏源”捕获。（疑似更新后出现此问题，尝试回退到上一版本仍无法解决）
![image](https://user-images.githubusercontent.com/61400426/184214330-2f1cf894-aff4-4726-a33f-92e1c3d386d2.png)
![image](https://user-images.githubusercontent.com/61400426/184214340-99e956b6-12d6-4780-91c4-ec9ba5550df8.png)

### 你期望发生的行为？

以前从SnapGenshin启动也可以正常被OBS“游戏源”捕获，哪怕是开启了帧率解锁。

### Snap Genshin 用户守则及相关的隐私条款

- [X] 我同意遵守 Snap Genshin 用户守则及相关的隐私条款

**Comment by Lightczx** [comment]
OBS需要管理员权限

**Comment by hoiyuyiu** [comment]
> OBS需要管理员权限

OBS一直都是管理员权限开启，但依然无法捕获由SnapGenshin启动的原神。捕获其他游戏是正常的

**Comment by hoiyuyiu** [comment]
又经测试，发现似乎与SnapGenshin无关，现在原生路径打开也是捕获到后卡顿一下然后丢失画面，正从其它方面排查问题

**Comment by hoiyuyiu** [comment]
> 又经测试，发现似乎与SnapGenshin无关，现在原生路径打开也是捕获到后卡顿一下然后丢失画面，正从其它方面排查问题

检查发现系微星小飞机导致无法捕获
