### ISSUE TITLE
[Bug]: 洞天宝钱不变化

### ISSUE THREAD

**Issue by icewolf-li** [DGP-Studio/Snap.Genshin#374]
### Windows 版本

版本21H2(操作系统内部版本19044.1826)

### Snap Genshin 版本

Snap Genshin 2022-Version 8.12 Build 53124

### Snap Genshin 用户设备ID

087AE43A64232A70749622DC2F392E41

### 发生了什么？

游戏内洞天宝钱上限提高，但是SG不变，显示的上限依旧是300，导致“其他提醒”设置80%还是240就提醒，{ 删除账号重新添加 重新下载SG 更新元数据 }以上方法都没用，反复尝试了好几次
![tmp55B5](https://user-images.githubusercontent.com/87270716/184368386-b96de495-48c7-490c-a9c4-2a3aec9fba15.png
![屏幕截图(110)](https://user-images.githubusercontent.com/87270716/184368631-c16df4ae-5747-4733-8083-69266d5a86ff.png)
)

### 你期望发生的行为？

能正常显示洞天宝钱，并且每次升级可以获取到真实数值，以便更好使用SG的提醒功能

### 相关的崩溃日志

```shell
无
```

### Snap Genshin 用户守则及相关的隐私条款

- [X] 我同意遵守 Snap Genshin 用户守则及相关的隐私条款

**Comment by Lightczx** [comment]
去米游社看看

**Comment by icewolf-li** [comment]
> 去米游社看看
![Screenshot_2022-08-12-23-15-25-196_com mihoyo hyperion jpg](https://user-images.githubusercontent.com/87270716/184386148-f20aaf98-5fd8-4575-a6fe-8d29f40aebf8.png)
