### ISSUE TITLE
[签到BUG]暂时无法解决，请留意后续SG官方通知

### ISSUE THREAD

**Issue by HYu7klyh42** [DGP-Studio/Snap.Genshin#375]
### Windows 版本

22000.856

### Snap Genshin 版本

2022 - version 8.12 Build 53125

### Snap Genshin 用户设备ID

62ADFCC9ACE9DC171404E63253075E27

### 发生了什么？

米游社签到提示如下
![image](https://user-images.githubusercontent.com/58126324/184450210-6126b43a-1851-4bfc-8425-ee394d9e19bf.png)

### 你期望发生的行为？

签到成功

### Snap Genshin 用户守则及相关的隐私条款

- [X] 我同意遵守 Snap Genshin 用户守则及相关的隐私条款

**Comment by rocks12138** [comment]
我也出现了这样的风控提示，进入米游社后发现没有签到。不排除签到米游社后台做了安全验证的可能

**Comment by smallsung1999** [comment]
同受到风控

**Comment by lannyroyaldoyle** [comment]
+1，受到风控

**Comment by RYX-3212103383** [comment]
+1受到风控，但是我用手机上的另一个应用可以签到（不是米游社）可能是DGP某些特征被定义为风险登录了

**Comment by Lightczx** [comment]
https://www.snapgenshin.com/documents/FAQ/about-sign-in.html

**Comment by Bilx-ZL** [comment]
同

**Comment by Masterain98** [comment]
请更新至最新版本，以缓解该问题，最新版本的 Snap Genshin 已经针对此问题进行了优化。
