### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by lin9632** [DGP-Studio/Snap.Genshin#379]
### Windows 版本

22000.856

### Snap Genshin 版本

2022-version 8.12 build 53125

### Snap Genshin 用户设备ID

7CFBF48A491EE568D193A118858A01CB

### 发生了什么？

签到提示风控
 
![微信图片编辑_20220814091301](https://user-images.githubusercontent.com/105112694/184518490-14b0418d-46e1-4068-8dc5-e9d31db74c0a.jpg)

### Snap Genshin 用户守则及相关的隐私条款

- [X] 我同意遵守 Snap Genshin 用户守则及相关的隐私条款

**Comment by Masterain98** [comment]
文档已说明
https://www.snapgenshin.com/documents/FAQ/about-sign-in.html

**Comment by lin9632** [comment]
谢谢
