### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by yxhuang** [DGP-Studio/Snap.Genshin#384]
### Windows 版本

22000.856

### Snap Genshin 版本

2022.8.12 Build 53125

### Snap Genshin 用户设备ID

896C73AE014CD0E79538C02C70364A6D

### 发生了什么？

签到时显示Risk code 375 账号被风控，无法自动签到。但我自己打开米游社可以正常手动签到。我的账号是自己新建的号，应该不存在风险，从开始玩到现在固定登录只有ipad这一个设备，无在任何其他设备登录过。

### Snap Genshin 用户守则及相关的隐私条款

- [X] 我同意遵守 Snap Genshin 用户守则及相关的隐私条款

**Comment by Lightczx** [comment]
#375
