### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ksupernami** [DGP-Studio/Snap.Genshin#391]
### Windows 版本

19044.1889

### Snap Genshin 版本

Version 8.17 Build 11356

### Snap Genshin 用户设备ID

49ECB518315B28B5484C0C0412ED4A28

### 发生了什么？

不能读取角色信息
![1](https://user-images.githubusercontent.com/77213279/185741860-2ac5c01b-060e-4496-821f-8fdf1e1957af.jpg)
![2](https://user-images.githubusercontent.com/77213279/185741864-bfc609fc-030e-4927-a591-4216b7b34503.jpg)
![3](https://user-images.githubusercontent.com/77213279/185741865-06091860-5c4f-4fab-a803-1a39a7c57a28.jpg)

### Snap Genshin 用户守则及相关的隐私条款

- [X] 我同意遵守 Snap Genshin 用户守则及相关的隐私条款

**Comment by Masterain98** [comment]
下载 [Cache.zip](https://resource.snapgenshin.com/Cache.zip) 解压于你的 Snap Genshin 目录并覆盖原有文件

**Comment by ksupernami** [comment]
没有用诶。角色和武器资料都是正常的。

**Comment by ksupernami** [comment]
![4](https://user-images.githubusercontent.com/77213279/185742516-1716c38f-2e12-4485-80bb-0bc323254ba3.jpg)

**Comment by Lightczx** [comment]
米游社的问题
