### ISSUE TITLE
[Bug]: wiki八重神子文案错误

### ISSUE THREAD

**Issue by dozbamb** [DGP-Studio/Snap.Genshin#392]
### Windows 版本

19044.1889

### Snap Genshin 版本

Ver 8.20 Build 41688

### Snap Genshin 用户设备ID

84EEC5042B85550FF7620EAE4ECFA610

### 发生了什么？

wiki角色资料八重神子命座二描述错误，与命座三重复

### 你期望发生的行为？

修正文案描述

### Snap Genshin 用户守则及相关的隐私条款

- [X] 我同意遵守 Snap Genshin 用户守则及相关的隐私条款

**Comment by Lightczx** [comment]
@Masterain98

**Comment by AlbertWen-AW** [comment]
实际上不止八重神子，所有角色的二命描述都与三命相同了

**Comment by Masterain98** [comment]
收到问题，会尽快处理

**Comment by Masterain98** [comment]
fixed
Masterain98/ghhw-genshin-spider@c2f8771b40439163a1facca2399eb09b618aa793
