### ISSUE TITLE
[Bug]: 角色和武器基础数值描述故障，角色二命的描述变成三命了，周常材料不显示

### ISSUE THREAD

**Issue by AlbertWen-AW** [DGP-Studio/Snap.Genshin#393]
### Windows 版本

Windows 10 19045.1889

### Snap Genshin 版本

Snap Genshin 2022 - version 8.20 Build 41688

### Snap Genshin 用户设备ID

241AF3BC21C6D5F57C2B594AA38A4732

### 发生了什么？

周常材料不显示：
![image](https://user-images.githubusercontent.com/106954672/185774290-df20084a-dc17-44d9-b01d-1b5ae2ffa93d.png)
角色基础数值显示异常（所有角色都是）
![image](https://user-images.githubusercontent.com/106954672/185774333-4bd8a6b6-3cab-4937-83af-32b8da12eb5d.png)
角色命座显示异常（所有角色都是 二命与三命重复）
![image](https://user-images.githubusercontent.com/106954672/185774365-7e18f33e-e367-4290-9261-7d938a85019a.png)
武器基础数值显示异常（或者叫不美观？如果不打算显示空白位置的数据建议删除这一行）
![image](https://user-images.githubusercontent.com/106954672/185774396-f5a012b3-6cf1-454f-8db2-ac2fb3a90d4f.png)

### 你期望发生的行为？

修正上述问题

### Snap Genshin 用户守则及相关的隐私条款

- [X] 我同意遵守 Snap Genshin 用户守则及相关的隐私条款

**Comment by Lightczx** [comment]
Fixed

**Comment by AlbertWen-AW** [comment]
emm命座描述错误的还没修复

**Comment by Lightczx** [comment]
由元数据控制会在后续元数据更新中提供修复

**Comment by Masterain98** [comment]
请在设置中更新元数据以获取最新信息版本的数据
