### ISSUE TITLE
[Bug]: WIKI 数据错误

### ISSUE THREAD

**Issue by ame-code** [DGP-Studio/Snap.Genshin#394]
### Windows 版本

19041.208

### Snap Genshin 版本

2022.8.21.13512

### Snap Genshin 用户设备ID

D2A04CEBDFB4C83ECBF30530617D2530

### 发生了什么？

角色资料里雷电将军的天赋“殊胜之御体”顶替了原本命座1的位置及文本描述，同时雷电将军所有命座图标及名称都后退了一格（命座1的图标和名称出现在了命座2的位置），命座6消失
实际情况如下：

天下名物狩
突破单手剑和长柄武器时，消耗的摩拉数量减少50%。

暂缺
无法参与料理

万千的愿望
队伍中附近的角色获得元素晶球或元索微粒时，会为诸愿百眼之轮积费2层原力。
该效果每3秒至多触发一次。
——————————————（以上为天赋，以下为命座）
（命座1）殊胜之御体
基于元索充能效率超过100%的部分，每1%使雷电将军获得下列效果:
梦想一心状态提供的元素能量恢复提高0.6%;
雷元索伤害加成提升0.4%。
（命座2）恶曜卜词
奥义梦想真说的梦想-刀与梦想-心状态下的雷电将军的攻击将无视敌人60%的防御力。
（命座3）斩铁断金
奥义梦想真说的梦想-刀与梦想-心状态下的雷电将军的攻击将无视敌人60%的防御力。
（命座4）真影旧事
奥义梦想真说的技能等级提高3级。
至多提升至15级。
（命座5）誓奉常道
奥义梦想真说施加的梦想-一心状态结束后， 附近的队伍中所有角色(不包括香电将军自2)的攻
击力提升30%，持续10秒。
（命座6）凶将显形
神变恶曜开眼的技能等级提高3级。
至多提升至15级。

### Snap Genshin 用户守则及相关的隐私条款

- [X] 我同意遵守 Snap Genshin 用户守则及相关的隐私条款

**Comment by Lightczx** [comment]
@Masterain98

**Comment by Masterain98** [comment]
已知问题，即将修复

**Comment by Masterain98** [comment]
fixed
Masterain98/ghhw-genshin-spider@c2f8771b40439163a1facca2399eb09b618aa793
Masterain98/ghhw-genshin-spider@25dc6d2f84bb5e0379163691c4f0b2a3e1cece79

**Comment by ame-code** [comment]
更新失败，重启依然显示下图通知
![Snipaste_2022-08-23_14-10-16](https://user-images.githubusercontent.com/71199825/186083669-cc91ea28-4051-4d91-aedd-28e1385bc2d9.png)

**Comment by ame-code** [comment]
> fixed [Masterain98/ghhw-genshin-spider@c2f8771](https://github.com/Masterain98/ghhw-genshin-spider/commit/c2f8771b40439163a1facca2399eb09b618aa793) [Masterain98/ghhw-genshin-spider@25dc6d2](https://github.com/Masterain98/ghhw-genshin-spider/commit/25dc6d2f84bb5e0379163691c4f0b2a3e1cece79)
> 
> 请在设置中更新元数据以获取最新信息版本的数据

更新失败，重启依然显示下图通知
![Snipaste_2022-08-23_14-10-16](https://user-images.githubusercontent.com/71199825/186083923-7b8fbe8c-9c02-4baf-8e5a-9fb9dc555a52.png)

**Comment by ame-code** [comment]
元数据已更新，显示正常
![Snipaste_2022-08-23_14-28-56](https://user-images.githubusercontent.com/71199825/186086500-aa214b88-f09c-4883-905d-a1c207a3c472.png)
