### ISSUE TITLE
[Bug]: Wiki 宵宫命座信息数据错误

### ISSUE THREAD

**Issue by tangtangebusi** [DGP-Studio/Snap.Genshin#396]
### Windows 版本

25182.1000

### Snap Genshin 版本

2022.8.21.13512

### Snap Genshin 用户设备ID

1FD2E8FEFB0E2BE08456F1BADFD4B423

### 发生了什么？

宵宫2命的描述信息有误  
错误信息为：描述和3命效果一致  
应为：宵宫的火元素伤害造成暴击后的6秒内，宵宫获得25%火元素伤害加成。宵宫处于队伍后台时，同样能获得该效果。

### 你期望发生的行为？

描述正确即可

### Snap Genshin 用户守则及相关的隐私条款

- [X] 我同意遵守 Snap Genshin 用户守则及相关的隐私条款

**Comment by Masterain98** [comment]
Duplicate of #392

**Comment by Masterain98** [comment]
fixed Masterain98/ghhw-genshin-spider@c2f8771b40439163a1facca2399eb09b618aa793
