### ISSUE TITLE
[Bug]: 祈愿记录的代理模式刷新功能无法获取

### ISSUE THREAD

**Issue by heinu112** [DGP-Studio/Snap.Genshin#403]
### Windows 版本

19044.1889

### Snap Genshin 版本

2022.8.24 18371

### Snap Genshin 用户设备ID

FB833B02CE05552E1C7E4423FFC7433F

### 发生了什么？

代理设置格式错误导致无法正常刷新祈愿记录
![1](https://user-images.githubusercontent.com/81513657/186499635-03f25fa1-4045-4c1f-92fb-4b55794be683.png)

### Snap Genshin 用户守则及相关的隐私条款

- [X] 我同意遵守 Snap Genshin 用户守则及相关的隐私条款

**Comment by Lightczx** [comment]
我们使用`18372`端口进行代理

**Comment by Lightczx** [comment]
https://github.com/DGP-Studio/Snap.Genshin/blob/a5cc4f144e3d1ab92f0d58c9fb9ef250dbfebd74/DGP.Genshin/Service/GachaStatistic/GachaLogUrlProvider.cs#L124

**Comment by JrantKing** [comment]
我这里也是，软件设置完系统代理后怎么都获取不到抽卡记录，就一直卡在那里

**Comment by heinu112** [comment]
> 我们使用`18371`端口进行代理

但是依旧无法正常刷新祈愿记录，应该是软件设置的系统代理有bug
应该是设置错误导致无法代理
我手动改成这样就好了
![1](https://user-images.githubusercontent.com/81513657/186954775-2c03d26e-b0b7-4fa3-be7b-91f5946344fa.png)

**Comment by Lightczx** [comment]
https://github.com/DGP-Studio/Snap.Hutao.GachaLog.UrlFinder
