### ISSUE TITLE
[Bug]: 更新版本后自动签到或者点击签到均不工作

### ISSUE THREAD

**Issue by Milk5253** [DGP-Studio/Snap.Genshin#407]
### Windows 版本

19044.1889

### Snap Genshin 版本

v8.24 build 18731

### Snap Genshin 用户设备ID

3245E6DB86F933AD9A16C657583FBA94

### 发生了什么？

自动签到或者点击签到均不工作，点击按钮没有任何反应，包括游戏内邮件和win10通知
同时其他功能例如实时便签正常

### Snap Genshin 用户守则及相关的隐私条款

- [X] 我同意遵守 Snap Genshin 用户守则及相关的隐私条款

**Comment by Milk5253** [comment]
换成低版本的程序能显示账号收到风控

**Comment by Mini-suger** [comment]
还是不行

**Comment by Lightczx** [comment]
签到功能由于米游社的邪恶检验，我们决定不再对该功能进行维护
