### ISSUE TITLE
建议设置一个取消检查更新按钮

### ISSUE THREAD

**Issue by 2ndElemet** [DGP-Studio/Snap.Genshin#41]
建议设置一个取消检查更新按钮,
因为当前版本自动更新失败,但每次打开都要检查更新,
不走代理的情况下,有时候初始化程序很慢,且每次都会有弹窗.

**Comment by Lightczx** [comment]
弹窗已经取消，但是前端UI的阻塞仍需要等待下一个版本更新解决

**Comment by Lightczx** [comment]
https://github.com/DGP-Studio/Snap.Genshin/releases/tag/2021.11.11.17
