### ISSUE TITLE
[Bug]: 米游社无法签到

### ISSUE THREAD

**Issue by Dawnwalker666** [DGP-Studio/Snap.Genshin#411]
### Windows 版本

版本21H2 （操作系统内部版本19044.1889）

### Snap Genshin 版本

Snap Genshin 2022 - Version 8.26 Build 5230

### Snap Genshin 用户设备ID

2644D12006E6CF2DFE988008041E5E3E

### 发生了什么？

米游社无法签到，详见录像
注意，并非签到而不通知，而是无法签到。未查明具体原因。
https://user-images.githubusercontent.com/49862610/187081642-daef9465-3733-449e-8e64-ff9e6758a619.mp4

### 你期望发生的行为？

修复

### 相关的崩溃日志

```shell
无，仅仅是无法签到
```

### Snap Genshin 用户守则及相关的隐私条款

- [X] 我同意遵守 Snap Genshin 用户守则及相关的隐私条款

**Comment by Dawnwalker666** [comment]
如果这里看不了视频。
点这个https://streamable.com/32b9b3

**Comment by Bilx-ZL** [comment]
xs，那个签到按钮现在点击没反应，漏了4天，今天才发现。20原石没了

**Comment by Lightczx** [comment]
签到功能已经不再维护
