### ISSUE TITLE
[Bug]: 珊瑚宫心海天赋和命座错误

### ISSUE THREAD

**Issue by AlbertWen-AW** [DGP-Studio/Snap.Genshin#413]
### Windows 版本

19045.1889

### Snap Genshin 版本

Snap Genshin 2022 - version 8.26 Build 5230

### Snap Genshin 用户设备ID

241AF3BC21C6D5F57C2B594AA38A4732

### 发生了什么？

如图，Snap Genshin 角色资料中，珊瑚宫心海的天赋和命座错误
![image](https://user-images.githubusercontent.com/106954672/187353182-6adb1bfc-8886-4a85-bb11-968cca080dbf.png)
![image](https://user-images.githubusercontent.com/106954672/187353251-011fd4b0-337e-48dc-a2ba-3558ab03fd04.png)
![image](https://user-images.githubusercontent.com/106954672/187353362-bc8bc2f5-2331-44f9-a9c1-59c720857994.png)

### 你期望发生的行为？

修复上述错误

### Snap Genshin 用户守则及相关的隐私条款

- [X] 我同意遵守 Snap Genshin 用户守则及相关的隐私条款

**Comment by Masterain98** [comment]
Fix at Masterain98/ghhw-genshin-spider@ef04804aa55775957eb9662e3baf1f4d24a16291
