### ISSUE TITLE
[Bug]: 代理模式无法正常刷新祈愿记录

### ISSUE THREAD

**Issue by PJnoeru** [DGP-Studio/Snap.Genshin#418]
### Windows 版本

19044.1889（21H2）

### Snap Genshin 版本

8.26 build5230

### Snap Genshin 用户设备ID

86AE39AB5AECD387037C879C14B38A96

### 发生了什么？

在单击（代理模式刷新）后确认系统代理为（http=localhost:18371;https=localhost:18371）后，在游戏中打开了祈愿功能中的的历史记录按钮，应用程序依然显示（获取抽卡链接中）提示，游戏已正常加载出历史记录

### 你期望发生的行为？

尝试使用了Genshin-Wish-Export的代理模式刷新，以排除其他代理软件的问题，但结果很遗憾，Genshin-Wish-Export正常的刷新历史数据
希望后期Snap Genshin可以修复该问题，因其无法正常刷新且一直显示提示（获取抽卡链接中），故只能关闭窗口尝试退出

### Snap Genshin 用户守则及相关的隐私条款

- [X] 我同意遵守 Snap Genshin 用户守则及相关的隐私条款

**Comment by Lightczx** [comment]
#403

**Comment by PJnoeru** [comment]
根据#403的相关提示：
![image](https://user-images.githubusercontent.com/41642563/187871618-65fee8b4-ea89-4d09-84f9-7b2d66649b91.png)

并验证Genshin-Wish-Export的相关代理设置情况
![image](https://user-images.githubusercontent.com/41642563/187871459-5b6b1c48-6af4-4888-be6f-58f0e184b45a.png)

确实可以通过手动更改代理设置来达到正常使用的情况，但是该问题应在后续版本中得到修复
![image](https://user-images.githubusercontent.com/41642563/187875373-44d26eb7-5d58-4df7-a9a7-5f3d13e87f63.png)

**Comment by Lightczx** [comment]
https://github.com/DGP-Studio/Snap.Hutao.GachaLog.UrlFinder
