### ISSUE TITLE
[Bug]: 代理模式与Adguard+Firefox不兼容

### ISSUE THREAD

**Issue by littlef0x** [DGP-Studio/Snap.Genshin#419]
### Windows 版本

22000.856

### Snap Genshin 版本

2022.8.26.5230

### Snap Genshin 用户设备ID

7F71D6170D9C5396D63A5F1F0FA2B20A

### 发生了什么？

我已了解3.0版本祈愿记录保存方式改动，需要使用代理模式获取。
以下内容我尽力还原每一步操作过程，但因为是事后整理，不排除有细节遗漏。

1. 点击“代理模式刷新”，提示安装证书，选择“否”，之后发现Firefox无法访问网页，错误代码SEC_ERROR_UNKNOWN_ISSUER
![图片](https://user-images.githubusercontent.com/32670075/187886925-8c6aabeb-b52e-43b6-b12f-d3046d1dc069.png)
2. 再次点击“代理模式刷新”，安装证书，Firefox依然无法访问网页，此时发现Edge正常
3. 关闭Snap Genshin，重启系统（Adguard运行，Snap Genshin未运行），Firefox依然无法访问网页
4. 停用Adguard，Firefox恢复正常，再启用Adguard，再次无法访问
5. 停用Adguard，在Adguard设置中重新安装证书，再启用Adguard，Firefox恢复正常
6. 打开Snap Genshin，再次开次代理模式，Firefox首次访问某些网站时报错PR_END_OF_FILE_ERROR，刷新后正常，此时查看证书为Titanium（Snap Genshin的证书）
![图片](https://user-images.githubusercontent.com/32670075/187888342-e1055932-6ec5-4377-aac2-80cc55ddc9bf.png)
7. 现在的状态是，Snap Genshin代理打开时，访问网站显示的证书是Titanium，同时首次访问网站报PR_END_OF_FILE_ERROR。关闭Snap Genshin，访问网站显示的证书是Adguard，不报PR_END_OF_FILE_ERROR

我个人推测因为Firefox的证书是独立保存的，不使用系统证书，Snap Genshin安装证书没有安装到Firefox，导致MITM无法信任。但是不知道怎么解释首次使用后退出Snap Genshin依然无法上网，然后重新安装Adguard证书后又可以上网的情况。
此处Adguard指Adguard for Windows，版本7.10.2，并非浏览器插件。

不知是否可以解决，如果不能解决，建议在文档中加入相关提示，以免其他人遇到相同情况不知道怎么操作。

### Snap Genshin 用户守则及相关的隐私条款

- [X] 我同意遵守 Snap Genshin 用户守则及相关的隐私条款

**Comment by Lightczx** [comment]
https://github.com/DGP-Studio/Snap.Hutao.GachaLog.UrlFinder
