### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by fuchen828** [DGP-Studio/Snap.Genshin#422]
### Windows 版本

22000.856

### Snap Genshin 版本

2022.8.26

### Snap Genshin 用户设备ID

4A1AD6A2CB07D60013408A60D3442F33

### 发生了什么？

已点击更新元数据及祈愿记录，祈愿记录不显示甘雨up

### 你期望发生的行为？

提供元数据替换文件或增加元数据更新成功反馈

### Snap Genshin 用户守则及相关的隐私条款

- [X] 我同意遵守 Snap Genshin 用户守则及相关的隐私条款

**Comment by Lightczx** [comment]
已经更新
