### ISSUE TITLE
[Bug]: Installer 出现编码问题

### ISSUE THREAD

**Issue by SteveXu9102** [DGP-Studio/Snap.Genshin#423]
### Windows 版本

22000.918

### Snap Genshin 版本

未知

### Snap Genshin 用户设备ID

未知

### 发生了什么？

官网下载Snap.Genshin.Installer.exe，启动后闪退
后尝试在管理员模式下用Powershell启动
出现如图报错
![B2PT I2YTH9833)DRNS_LWL](https://user-images.githubusercontent.com/68725147/189463507-d1810a88-1a03-4427-b820-5983192970b0.png)
推测问题可能为Python可执行文件的编码错误导致的闪退

### Snap Genshin 用户守则及相关的隐私条款

- [X] 我同意遵守 Snap Genshin 用户守则及相关的隐私条款

**Comment by Masterain98** [comment]
[installer2022090901.zip](https://github.com/DGP-Studio/Snap.Genshin/files/9539394/installer2022090901.zip)
麻烦试一下这个版本

**Comment by SteveXu9102** [comment]
很遗憾，编码是没问题了，但新问题又出现了
请检查外部包requests是否一并被编译进程序







------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;; 
Date: 2022年9月10日(星期六) 上午10:04
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: Re: [DGP-Studio/Snap.Genshin] [Bug]: Installer 出现编码问题 (Issue #423)





 
installer2022090901.zip
 麻烦试一下这个版本

**Comment by Masterain98** [comment]
我的打包环境有点问题。正在改。

**Comment by Masterain98** [comment]
> 

[installer20220909002.zip](https://github.com/DGP-Studio/Snap.Genshin/files/9539414/installer20220909002.zip)
重新打包了一下，麻烦试试

**Comment by SteveXu9102** [comment]
啊这？






------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;; 
Date: 2022年9月10日(星期六) 上午10:25
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: Re: [DGP-Studio/Snap.Genshin] [Bug]: Installer 出现编码问题 (Issue #423)





   
installer20220909002.zip
 重新打包了一下，麻烦试试

**Comment by Masterain98** [comment]
> 啊这？
> […](#)
> ------------------&nbsp;Original&nbsp;------------------ From: ***@***.***&gt;; Date: 2022年9月10日(星期六) 上午10:25 To: ***@***.***&gt;; Cc: ***@***.***&gt;; ***@***.***&gt;; Subject: Re: [DGP-Studio/Snap.Genshin] [Bug]: Installer 出现编码问题 (Issue #423) installer20220909002.zip 重新打包了一下，麻烦试试 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

是还有什么问题吗？

**Comment by SteveXu9102** [comment]
不好意思图片没上传上去
![AOZLK8%6ZYEQWCPA{XY_XEG](https://user-images.githubusercontent.com/68725147/189466006-cf1446df-6ce6-40d8-8687-71f158975e87.png)

**Comment by Masterain98** [comment]
> 不好意思图片没上传上去 ![AOZLK8%6ZYEQWCPA{XY_XEG](https://user-images.githubusercontent.com/68725147/189466006-cf1446df-6ce6-40d8-8687-71f158975e87.png)

你在PowerShell中执行一下 `[Environment]::GetFolderPath("Desktop")`看下是什么结果

**Comment by SteveXu9102** [comment]
![L V9@TT~ECSYOSTGO{E6P T](https://user-images.githubusercontent.com/68725147/189466158-8731cb74-e842-4bab-958a-dcb68a86e5a4.png)

**Comment by Masterain98** [comment]
> ![L V9@TT~ECSYOSTGO{E6P T](https://user-images.githubusercontent.com/68725147/189466158-8731cb74-e842-4bab-958a-dcb68a86e5a4.png)

是中文路径吗？

**Comment by SteveXu9102** [comment]
是的




------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;; 
Date: 2022年9月10日(星期六) 上午10:57
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: Re: [DGP-Studio/Snap.Genshin] [Bug]: Installer 出现编码问题 (Issue #423)





  

  
是中文路径吗？

**Comment by Masterain98** [comment]
> 是的
> […](#)
> ------------------&nbsp;Original&nbsp;------------------ From: ***@***.***&gt;; Date: 2022年9月10日(星期六) 上午10:57 To: ***@***.***&gt;; Cc: ***@***.***&gt;; ***@***.***&gt;; Subject: Re: [DGP-Studio/Snap.Genshin] [Bug]: Installer 出现编码问题 (Issue #423) 是中文路径吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

PS中执行一下`chcp`看看结果是什么
![image](https://user-images.githubusercontent.com/10614984/189466225-4a0393b3-82de-4a90-a63c-6a03c559a882.png)

**Comment by SteveXu9102** [comment]
活动代码页936

**Comment by SteveXu9102** [comment]
是要改成65001执行吗？

**Comment by Masterain98** [comment]
[installer20220909003.zip](https://github.com/DGP-Studio/Snap.Genshin/files/9539472/installer20220909003.zip)
麻烦试下这个版本看是否可以解决

**Comment by SteveXu9102** [comment]
成功执行。
感谢！

**Comment by Masterain98** [comment]
> 成功执行。 感谢！

麻烦告知一下最后一次显示的`trying xxx`是哪种编码？
另外可以在语言设置中启用`UTF-8`支持
![image](https://user-images.githubusercontent.com/10614984/189466512-757527af-047e-4c0c-8f90-910a9939320b.png)

**Comment by SteveXu9102** [comment]
最后一次尝试的编码是GB2312




------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;; 
Date: 2022年9月10日(星期六) 中午11:09
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: Re: [DGP-Studio/Snap.Genshin] [Bug]: Installer 出现编码问题 (Issue #423)





  
成功执行。 感谢！
  
麻烦告知一下最后一次显示的trying xxx是哪种编码？
 另外可以在语言设置中启用UTF-8支持
