### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Weizili114514** [DGP-Studio/Snap.Genshin#424]
### Windows 版本

Windows 11 专业工作站版 Insider Preview25193.1000

### Snap Genshin 版本

Snap Genshin 2022 Version 8.26 Build 5230

### Snap Genshin 用户设备ID

4B90B8AAB7529C3DD416F7BB1B2D7585

### 发生了什么？

在我已经安装国际服转换插件的情况下提示无法转换
全程录屏链接：https://pan.baidu.com/s/1xMV2wIb9amo_093pOqbT3g?pwd=snap 
提取码：snap 

### 你期望发生的行为？

转换到国际服

### 相关的崩溃日志

```shell
链接：https://pan.baidu.com/s/1xMV2wIb9amo_093pOqbT3g?pwd=snap 
提取码：snap
```

### Snap Genshin 用户守则及相关的隐私条款

- [X] 我同意遵守 Snap Genshin 用户守则及相关的隐私条款

**Comment by Lightczx** [comment]
@dawnfz
