### ISSUE TITLE
[Bug]: 签到失败问题

### ISSUE THREAD

**Issue by restarteded** [DGP-Studio/Snap.Genshin#428]
### Windows 版本

19042.1076

### Snap Genshin 版本

2022.8.26.5230

### Snap Genshin 用户设备ID

65139561F099A95DC4462E58358F3379

### 发生了什么？

在快捷方式中设置最大化无法生效
但是不最大化会导致部分菜单无法显示
试图在setting.json中设置无效

### 你期望发生的行为？

如果可以请添加相应最大化启动设置

### Snap Genshin 用户守则及相关的隐私条款

- [X] 我同意遵守 Snap Genshin 用户守则及相关的隐私条款

**Comment by restarteded** [comment]
签到也不正常，我试了两天

**Comment by AlbertWen-AW** [comment]
> 签到也不正常，我试了两天

签到的东西由于米游社加了验证，早就说不继续支持了
