### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by pik553** [DGP-Studio/Snap.Genshin#431]
### Windows 版本

19042.1466

### Snap Genshin 版本

2022.8.26 build 5230

### Snap Genshin 用户设备ID

46BD1055908AA443884A7D362BBAE11E

### 发生了什么？

椰羊导出的ULAF1.1成就json文件，可以导入到snap Hutao，却无法导入到snap genshin。显示“导入失败，导入的数据中包含了不正确的项目”。

### Snap Genshin 用户守则及相关的隐私条款

- [X] 我同意遵守 Snap Genshin 用户守则及相关的隐私条款

**Comment by Lightczx** [comment]
SG的成就系统的导入功能不再维护
