### ISSUE TITLE
无法打开软件

### ISSUE THREAD

**Issue by ZhuJyi** [DGP-Studio/Snap.Genshin#53]
第一次打开软件无法获取角色信息和祈愿记录，随后闪退，之后就无法打开并且报一下的错误

Snap Genshin - 2021.11.3.18
System.Windows.Markup.XamlParseException: “对类型“DGP.Genshin.Controls.TitleBarButtons.UserInfoTitleBarButton”的构造函数执行符合指定的绑定约束的调用时引发了异常。”，行号为“622”，行位置为“14”。

**Comment by Lightczx** [comment]
重新解压压缩包再试试

**Comment by Lightczx** [comment]
已经定位问题，在根目录下创建`cookie.dat`文件，并将cookie保存在此处可以临时解决问题

**Comment by Lightczx** [comment]
https://github.com/DGP-Studio/Snap.Genshin/releases/tag/2021.11.4.4
