### ISSUE TITLE
祈愿记录功能里，下拉选择祈愿池中能否加入常驻池选择

### ISSUE THREAD

**Issue by herderich** [DGP-Studio/Snap.Genshin#54]
![image](https://user-images.githubusercontent.com/23006594/140317893-ab836901-796c-46c8-9c2d-6c71933a167e.png)

祈愿记录中能下拉选择每个【角色活动池】查看详细角色和武器获取记录，但【常驻池】只能在上方看到五星记录。希望能够把【常驻池】也加进去，查看详细获取记录，谢谢！

**Comment by Lightczx** [comment]
https://github.com/DGP-Studio/Snap.Genshin/releases/tag/2021.11.6.34
