### ISSUE TITLE
日常材料和服务器同步

### ISSUE THREAD

**Issue by SprinBrother** [DGP-Studio/Snap.Genshin#57]
由于计算机本地时间比服务器晚一天,所以日常材料显示的是前一天的材料信息.
可不可以把日常材料的算法和服务器同步

**Comment by Lightczx** [comment]
感觉加一个手动选择日期的功能就够了
时间不好与服务器同步

**Comment by SprinBrother** [comment]
可以自己选择星期几也可以

**Comment by Lightczx** [comment]
https://github.com/DGP-Studio/Snap.Genshin/releases/tag/2021.11.6.34
