### ISSUE TITLE
关于反馈建议的功能制作进度

### ISSUE THREAD

**Issue by Lightczx** [DGP-Studio/Snap.Genshin#6]
感谢开发，现在看解包数据简单多了。

DataViewer 的一些功能建议：
1. 允许批量调整行间距
比如我现在查看 Weapon，WeaponProp 这一列会把每一行都撑得很大，看起来不美观
可能简单一些的解决办法：干脆在设置里加一个默认行间距，无论改文件的某一列内容有多少都不会撑大行间距
2. 允许不显示某些列
以 Weapon 为例，对于某些用户（比如我）来说，只需要看 WeaponType、RankLevel、WeaponBaseExp、Id、NameTextMapHash、DescTextMapHash 等信息，其他信息不是很需要。虽然目前版本可以把自己不需要的列的宽度拉小
这个设定最好可以保存（记录到 settings.json 内？）
3. 允许按照列排序，甚至是筛选
以 Weapon 为例，比如我想只查看 WEAPON_BOW 或者只查看 5 星武器，有排序就会比较方便
4. 允许搜索某个文件内部对应的文字（主要是对应的 hash）
还是以 Weapon 为例，比如我想找“以理服人”。“以理服人”四个字本身不在 WeaponExcelConfigData.json 内，是靠对应关系在 TextZHS.json 里找到的，但我希望能在选择语言为 TextZHS 时，在 Weapon 上直接搜到“以理服人”
5. Dialog 里的 TaleRole，有些有角色 ID，比如 1624，对比 NpcExcelConfigData.json 我们可以知道 1624 对应的 NPC 是常九爷。希望在使用 DataViewer 时，软件可以同时去 NpcExcelConfigData.json 寻找对应的角色 ID 并直接显示出来

_Originally posted by @Aniverse in https://github.com/DGP-Studio/Snap.Genshin/issues/1#issuecomment-778557699_

**Comment by Lightczx** [comment]
1.行高目前为固定值32pixel
2.筛选列功能正在制作
3.排序功能已经完成并实装，筛选功能正在测试
4.搜索功能较为复杂，短时间不会测试
5.对话人物映射已经实装

**Comment by Lightczx** [comment]
筛选列功能已经实装

**Comment by Aniverse** [comment]
感谢。我现在使用 2021.2.24.1 版本，用搜索框查找 TextHashMap 内容似乎没有反应？

另外还有个建议不知是否有必要开个新的 issue：有些文本比如 Fetters 里，有些文字有特殊的颜色：
`#<color=#37FFFF>派蒙：</color>猫咪和狗狗，你更喜欢哪一个？`
这个 color 可以改为显示对应的颜色，或者直接无视掉

**Comment by Lightczx** [comment]
颜色改变会在后面的版本中更新实现这个效果需要重写DataGridTextColumn控件，所以需要一些时间。
搜索textmaphash只能搜索数字编号，反向按文字查询会在下个版本实装
如果是搜索数字也没有反应则需要提交新的issue
另外目前点击出现的搜索项，表格视图不会自行跳转（没有这个功能，如果需要实现，会在下版本考虑）

**Comment by Lightczx** [comment]
颜色改变功能由于WPF平台的问题在短期内不可行
下版本将在映射时直接移除相关标签并保留内容
