### ISSUE TITLE
无法启动软件报错

### ISSUE THREAD

**Issue by EchoLfss** [DGP-Studio/Snap.Genshin#64]
第一进入一切正常,但是关闭后无法再次再开,并且在根目录生成一个   时间-crash.log  的文件
这是报错信息
[2021-11-19 21-37-47-crash.log](https://github.com/DGP-Studio/Snap.Genshin/files/7570582/2021-11-19.21-37-47-crash.log)
)

**Comment by Lightczx** [comment]
https://github.com/DGP-Studio/Snap.Genshin/issues/55#issuecomment-961596868

**Comment by EchoLfss** [comment]
2021.11.17.4发布的版本,

> [第55章（评论）](https://github.com/DGP-Studio/Snap.Genshin/issues/55#issuecomment-961596868)

**Comment by Lightczx** [comment]
提供的cookie必须包含accout_id字段

**Comment by Lightczx** [comment]
打开 `cookie.dat` 文件，查找是否存在 account_id 相关字样，不存在需要删除 `cookie.dat` `cookielist.dat` 文件 重新启动

**Comment by EchoLfss** [comment]
没有account_id,删除cookie.dat和cookielist.dat后可以启动但是还是要求输入token
![lalala2021-11-19_21-49-09](https://user-images.githubusercontent.com/89125944/142633184-fb3eebe4-f375-478d-a778-6d7637fa8e06.png)
,

**Comment by EchoLfss** [comment]
是否是我的token有误,我输入之后无法确认,但是我点击取消一直加载进去显示的是我已登入
![lalala2021-11-19_21-51-38](https://user-images.githubusercontent.com/89125944/142633486-50afd91a-06bd-4977-aa21-496af7caf5bf.png)
![lalala2021-11-19_21-51-59](https://user-images.githubusercontent.com/89125944/142633516-79a44cc5-bc5a-4e4c-8756-21ef9125b904.png)

**Comment by Lightczx** [comment]
没有account_id 的cookie 是未登录态的，你需要重新登录 [米哈游通行证](https://user.mihoyo.com/) 和 [原神BBS](https://bbs.mihoyo.com/ys/) 重新获取cookie

**Comment by Lightczx** [comment]
另外是account_id 不是 accout_id

**Comment by EchoLfss** [comment]
![lalala2021-11-19_21-53-27](https://user-images.githubusercontent.com/89125944/142633890-0d85fd16-4c35-4d41-b917-acca3e69ca22.png)
是cookie的值全输入对吧,我去试试自动获取

**Comment by Lightczx** [comment]
这个cookie明显是不对的，需要重新登录了

**Comment by EchoLfss** [comment]
问题解决了,是我的米游社登入过期了,,,,.,,,重新登入获取就完美解决了   😘谢谢大佬

**Comment by wmjgh** [comment]
解决了
