### ISSUE TITLE
DGP.Genshin.Mate点在桌面显示没反应

### ISSUE THREAD

**Issue by czwzy2017** [DGP-Studio/Snap.Genshin#67]
我勾上在桌面显示，好像没什么变化。另外，DGP.Genshin.Mate可以添加显示探索派遣的剩余时间吗

**Comment by Lightczx** [comment]
> 我勾上在桌面显示，好像没什么变化。
1. 将 `在桌面上显示` 去除勾选
2. 重启 Windows资源管理器
3. 重新勾选 `在桌面上显示`

注意：如果开启了其他会嵌入桌面的程序（Wallpaper Engine等），是无法与其同时显示的
> 另外，DGP.Genshin.Mate可以添加显示探索派遣的剩余时间吗
* 暂时没有这方面的打算，因为支持多人显示，如果所有账户全部显示完整内容会导致窗口过大
