### ISSUE TITLE
Windows 11 DGP.Genshin.Mate 桌面部件不显示

### ISSUE THREAD

**Issue by Xm798** [DGP-Studio/Snap.Genshin#79]
勾选“在桌面上显示”，无任何效果。
![image](https://user-images.githubusercontent.com/48074861/144817354-eb52ff02-85a6-4a3e-8ed8-c63f0637a3dd.png)
系统版本：`Windows 11 Pro for Workstations 21H2 22000.318`
![image](https://user-images.githubusercontent.com/48074861/144817508-fe4d28b0-5051-4299-992a-9344b771c6c3.png)
![1](https://user-images.githubusercontent.com/48074861/144817967-7c18295c-1cf7-4566-9f9f-83f8ffafd36d.png)

**Comment by Lightczx** [comment]
#67

**Comment by Xm798** [comment]
> #67

啊这 竟然是Wallpaper Engine的原因。但我这边使用滴答清单和[CountBoard](https://github.com/Gaoyongxian666/CountBoard)的桌面部件是正常的，或许有计划支持一下与we共存嘛？

**Comment by Lightczx** [comment]
目前还不知道如何实现共存

**Comment by Xm798** [comment]
> 目前还不知道如何实现共存

尝试了一下，先开 DGP.Genshin.Mate，再开 WE 就好了。新的问题是，能否设置字体颜色？深色壁纸下很难看清。
![image](https://user-images.githubusercontent.com/48074861/144821293-673e81bf-96aa-4f27-8c5e-a71c3da14829.png)

**Comment by Lightczx** [comment]
字体颜色是和主题匹配的，目前没有添加修改颜色功能的计划

**Comment by Xm798** [comment]
> 字体颜色是和主题匹配的，目前没有添加修改颜色功能的计划

是与主程序的主题吗？将主程序主题改为深色，字体颜色也仍然是黑色。更改WINDOWS主题也无变化欸。

**Comment by Lightczx** [comment]
更改Windows的应用颜色主题才会改变颜色

**Comment by Lightczx** [comment]
fixed
