### ISSUE TITLE
一启动DGP.Genshin.exe就崩溃

### ISSUE THREAD

**Issue by a86582751** [DGP-Studio/Snap.Genshin#8]
[snap_genshin_crash.log](https://github.com/DGP-Studio/Snap.Genshin/files/6217517/snap_genshin_crash.log)
还是我使用的方法不对？

**Comment by Lightczx** [comment]
已经发现是框架的设计问题，启动时崩溃会在下个版本修复

**Comment by Lightczx** [comment]
使用方法始终是正确的：至少启动一次原神并查看抽卡界面，然后在原神关闭的情况下打开程序即可获取祈愿记录。

**Comment by Lightczx** [comment]
今天晚些时候会有更新
