### ISSUE TITLE
考虑在gitee搞一个release

### ISSUE THREAD

**Issue by icimence** [DGP-Studio/Snap.Genshin#80]
每次更新的时候都需要科学上网才能下载。可以考虑一下在gitee搞一个仓库专门放发行版本或者直接更新在gitee上对国内用户可能更友好一点。也可以考虑增加一个国内服务器的选项，GitHub更新每次都要重启好几次应用切换代理有点太麻烦了

**Comment by icimence** [comment]
呃呃呃，发现gitee已经有一个了，但是很久没有更新了。

**Comment by Lightczx** [comment]
未来会考虑恢复gitee源

**Comment by LetMeDecay** [comment]
https://download.fastgit.org/DGP-Studio/Snap.Genshin/releases/download/2021.12.11.6/Publish.zip

https://doc.fastgit.org/zh-cn/guide.html

可以直接用镜像仓检测更新

这里还有些其他的镜像仓

https://github.com/RC1844/FastGithub

**Comment by Lightczx** [comment]
#85

**Comment by Lightczx** [comment]
近期正在制作替换更新源的功能

**Comment by Lightczx** [comment]
已经做好了，下版本就会发布
