### ISSUE TITLE
无法正常查询角色信息与查看实时便笺

### ISSUE THREAD

**Issue by Lightczx** [DGP-Studio/Snap.Genshin#92]
由于米游社接口更新，目前无法正常查询角色信息与查看实时便笺，今天晚些时候我们将发布新的版本修复此问题

**Comment by denghahaxixi** [comment]
那启动游戏打不开是什么问题 谢谢 更新2021.12.22.30后就这样了 2021.12.24.7也一样 删除文件重试了也不行

**Comment by Lightczx** [comment]
启动启动器可以么？
