### ISSUE TITLE
祈愿导入功能暂时失效

### ISSUE THREAD

**Issue by Lightczx** [DGP-Studio/Snap.Genshin#93]
由于设计上的失误导致先版本无论如何导入祈愿记录都会失败，目前已经定位问题，会在下版本发布时修复

**Comment by nyano** [comment]
DGP.Genshin.Mate在【在桌面上显示】不能够保存配置。关掉重启后不记录重开，需要手点。
树脂数据需要点一下才会更新。是否可能设置为定时更新设定
【养成计算】是否可以设定为多角色统计选择（总计）
祈愿导入不能导入【genshin-wish-export】的数据，不知是否为上述版本的问题

**Comment by Lightczx** [comment]
Mate的问题不会进行任何调整
养成角色的统计可能会在后续版本加入

**Comment by Lightczx** [comment]
我们正准备对Mate进行重构

**Comment by Lightczx** [comment]
#94

**Comment by Lightczx** [comment]
fixed
