### ISSUE TITLE
新版本[测试]便签

### ISSUE THREAD

**Issue by nyano** [DGP-Studio/Snap.Genshin#98]
比旧版本缺失了多账号显示

**Comment by Lightczx** [comment]
直接显示多个账号不太美观
多账号的问题，我们还在讨论，可能会在小组件上加上切换账号的功能

**Comment by Lightczx** [comment]
小组件上同时也可能呈现其他的内容，但是我们还不确定如何呈现，也欢迎提一些意见

**Comment by nyano** [comment]
有多账号需求的,基本上都想直接显示多账户.考虑美观可以用折叠,设置个主账号,其他先折叠起来,手动扩展显示.如这种模式,希望保留能记忆设定 直接不折叠.

**Comment by Lightczx** [comment]
新版本已经以另一种方式支持了同时显示多账户
