### ISSUE TITLE
[疑难杂症] 标题栏 启动游戏 功能 无法 启动游戏

### ISSUE THREAD

**Issue by denghahaxixi** [DGP-Studio/Snap.Genshin#99]
从2021.12.11.6版本后的版本就一直无法打开"启动游戏"
必须退回到2021.12.11.6才恢复正常
试过很多办法无效 例如备份cookie和账号文件再删除重装

**Comment by denghahaxixi** [comment]
请问如何解决 谢谢

**Comment by Lightczx** [comment]
启动器可以打开么

**Comment by Lightczx** [comment]
有许多人都确认有问题，但是我毫无头绪，下面是启动相关的代码位置，有能力debug的去看看吧

https://github.com/DGP-Studio/Snap.Genshin/blob/901b0b1be041a2b51a1a3caca7f784ca724763f8/DGP.Genshin/Services/LaunchService.cs#L172

**Comment by Lightczx** [comment]
可以尝试一下删除 settings.json @denghahaxixi

**Comment by denghahaxixi** [comment]
删除了也没用 启动器正常打开 路径正常 其他功能都正常 只有这个打不开 搞了挺久了还解决不了 谢谢

**Comment by Lightczx** [comment]
最新版还有问题吗

**Comment by denghahaxixi** [comment]
谢谢 不过最新版还有这个问题 版本是2022.1.13(21) 系统是Win11 22471.1000

**Comment by Lightczx** [comment]
最好还是进群拿个debug版跑一下看看具体什么情况，目前有用的信息实在太少了，丝毫没有解决的头绪

**Comment by denghahaxixi** [comment]
那好的 谢谢 请问群在哪里

**Comment by denghahaxixi** [comment]
已经加了 谢谢

**Comment by denghahaxixi** [comment]
好耶！今天更新新版本启动游戏出来了！谢谢！
